load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "graphql_api_service",
    srcs = ["graphql_api_service.go"],
    importpath = "github.com/buildbarn/bb-portal/internal/api/http/graphql_api_service",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/api/http/loghandler",
        "//internal/database",
        "//internal/database/dbauthservice",
        "//internal/graphql",
        "//pkg/proto/configuration/bb_portal",
        "@com_github_99designs_gqlgen//graphql",
        "@com_github_99designs_gqlgen//graphql/playground",
        "@com_github_buildbarn_bb_storage//pkg/auth/configuration",
        "@com_github_buildbarn_bb_storage//pkg/clock",
        "@com_github_buildbarn_bb_storage//pkg/grpc",
        "@com_github_buildbarn_bb_storage//pkg/program",
        "@com_github_buildbarn_bb_storage//pkg/util",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
