{
 "title": "BB Portal - Overview",
 "description": "High level view of metrics from bbportal service",
 "tags": [
  "RBE",
  "BB-Portal"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "label": "Host", "query": { "query": "label_values(Host)" } }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Unique Test Executions",
   "type": "stat",
   "description": "Count the number of unique test targets seen during the time period.  Does not include cached results.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( group (buildbarn_portal_uncached_test_durations) by (Target))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action Cache Hit Rate",
   "type": "gauge",
   "description": "Current average across invocations",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (histogram_quantile(.9, sum by (le) (rate(buildbarn_portal_remote_cache_hit_rate_bucket[10m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Users",
   "type": "stat",
   "description": "the number of hosts sending invocations to bbportal",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( (group( buildbarn_portal_invocation_counts ) by (User)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Longest Build Duration Targets",
   "type": "table",
   "description": "These build target durations took the longest to execute during the time period.  Can include tests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, buildbarn_portal_slow_target_durations)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Targets > 2s",
   "type": "stat",
   "description": "Count of targets seen during the time period, excludes any targets that completed with a duration of less than 2 seconds",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( group( buildbarn_portal_slow_target_durations) by (Target))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Hosts",
   "type": "stat",
   "description": "Number of host machines sending invocations to bbportal. ",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(buildbarn_portal_invocation_counts) by (Host))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Failed Tests",
   "type": "timeseries",
   "description": "Rate of tests with a failed status over a 10minute period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10,rate( buildbarn_portal_uncached_test_durations{Status=\"FAILED\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Failing Tests",
   "type": "table",
   "description": "Top longest test duration executions with a status of failed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, buildbarn_portal_uncached_test_durations{Status=\"FAILED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Invocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Rate of Invocations by Host",
   "type": "timeseries",
   "description": "the rate of invocations over a 10 minute period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(buildbarn_portal_invocation_counts{Host=~\"$Host\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocations by Host",
   "type": "table",
   "description": "A count of invocations by Host",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "count(buildbarn_portal_invocation_counts) by (Host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocations by Step Label",
   "type": "table",
   "description": "A count of invocations by Step Label",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count(buildbarn_portal_invocation_counts) by (StepLabel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocations by User",
   "type": "table",
   "description": "A count of invocations by User",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "count(buildbarn_portal_invocation_counts) by (User)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Information",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "options": {
      "content": "<h1>Overview</h1>\n<p>\n  The overview dashboard captures a high level over-view of targets, tests and invocations across your infrastruture.\n</p>\n<h2>Action Cache Hit Rate</h2>\n<p>\n  I don't know if I'm calculating this correctly.  This metric is tracked using a histogram, and I'm trying to get an average across all invocations for the time period.\n</p>\n<h2>Invocations</h2>\n<p>\n  Invocations are tracked using a counter metric.\n</p>\nInvocations contain the following labels:\n<ul>\n  <li>Host</li>\n  <li>User</li>\n  <li>Step Label</li>\n</ul>"
     }
    }
   ]
  }
 ]
}