{
 "title": "BB Portal - Targets",
 "description": "Visualize Target Build Times",
 "tags": [
  "RBE",
  "BB-Portal"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "target", "label": "target", "query": { "query": "label_values(Target)" } }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Level Target Durations",
   "type": "timeseries",
   "description": "A breakdown of reported build durations per top level target",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//autonomy/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//docs/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//examples/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//experimental/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//firmware/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//hardware/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//jewels/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//kits/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//platforms/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//ros/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//services/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//sim/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//system/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//third_party/.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(buildbarn_portal_slow_target_durations{Target=~\"//tools/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Target Durations",
   "type": "timeseries",
   "description": "Chose a specific target you want to analyze using the dropdown variable",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg( buildbarn_portal_slow_target_durations {Target=~\"$target\"}) by (Target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Longest Build Duration Targets",
   "type": "table",
   "description": "The targets with the longest execution durations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, buildbarn_portal_slow_target_durations)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target Durations",
     "type": "text",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "options": {
      "content": "\n<p>In this context, target durations are a rough approximation of how long the target took to run from the client perspective as closely as we can track.  Target Durations are not tracked by default in the build event service.  Target duration is calculated by the bbportal instance.  This is done by noting the difference from recieving the target configured event to recieving the target completed event, so this is a measure of how long it took this action to execute from the client's perspective, but can also be influenced by network latency, bbportal load, client, load, etc.  It is just an approximation.<p>\n<p>\n We also ignore anything that executes in less than 2 seconds (2000ms) because we are really only interested in the outliers, so if you're looking for detailed timing metrics about a given target and you can't find the target here that is one possibly reason why.\n</p>\n<p>Additionally, we use a gauge metric to track durations and these metrics are scraped every 90 seconds by prometheus, so its just a sampling of last seen.  This is time series data so its captures a moment in time.  Its always possible that a really long execution duration was missed because it occured at the start of a scrape interval, and another event over-rode it by the end of the scrape interval. Its best to view this data over a period of time to look for changes</p>\n<ul>\n  <li>The <b>Top Level Target Durations</b> table shows an average of all targets within a certain path</li>\n  <li>\n    <p>You can look at an individual target(s) with the <b>Average Target Durations</b> Visualization</p>\n    <pre>Note: Use the dropdown variable to select a specific target or targets you want to examine more closely</pre>\n  </li>\n  <li>The <b>Top Longest Target Durations<b> shows the top k durations</li>\n</ul>\n<p>\n  To reduce the cardinality for tests, we only track a duration, not an outcome.  If you try to look back too far, the number of possible values may become too great for prometheus to handle.\n</p>"
     }
    }
   ]
  }
 ]
}