package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// TestResult holds the schema definition for the TestResult entity.
type TestResult struct {
	ent.Schema
}

// Fields of the TestResult.
func (TestResult) Fields() []ent.Field {
	return []ent.Field{
		field.Int32("run").Immutable(),

		field.Int32("shard").Immutable(),

		field.Int32("attempt").Immutable(),

		// The status of this test.
		field.String("status").Optional(),

		// Status Details.
		// Additional details about the status of the test. This is intended
		// for user display and must not be parsed.
		field.String("status_details").Optional(),

		// Cached locally.
		// True, if the reported attempt is taken from the tool's local cache.
		field.Bool("cached_locally").Optional(),

		field.Time("test_attempt_start").Optional(),

		field.Int64("test_attempt_duration_in_ms").Optional(),

		// Warnings generated by that test action.
		field.Strings("warning").Optional(),

		// Name of the strategy to execute this test action (e.g., "local", "remote").
		field.String("strategy").Optional(),

		// True, if the reported attempt was a cache hit in a remote cache.
		field.Bool("cached_remotely").Optional(),

		// The exit code of the test action.
		field.Int32("exit_code").Optional(),

		// The hostname of the machine where the test action was executed (in case
		// of remote execution), if known.
		field.String("hostname").Optional(),

		field.JSON("timing_breakdown", map[string]any{}).Optional(),

		// Per-output references from the BES TestResult.test_action_output
		// array. Stored as a map keyed by output name (e.g. "test.log",
		// "test.xml", "test.outputs__outputs.zip") where each value is a
		// map of {uri, digest, length} captured from build_event_stream.File.
		// Mirrors the timing_breakdown encoding shape so it surfaces through
		// the existing Map GraphQL scalar without needing entgql.Type or
		// other schema annotations.
		//
		// The frontend reads the map at render time and emits a download
		// link per entry. The data is already in BES; this just persists
		// it so the UI can query the URIs after the event is consumed.
		field.JSON("test_action_outputs", map[string]any{}).Optional(),
	}
}

// Edges of TestResult.
func (TestResult) Edges() []ent.Edge {
	return []ent.Edge{
		// Edge back to the test collection.
		edge.From("test_summary", TestSummary.Type).
			Ref("test_results").
			Required().
			Unique(),
	}
}

// Indexes of the TestResult.
func (TestResult) Indexes() []ent.Index {
	return []ent.Index{
		index.Edges("test_summary"),
	}
}

// Mixin of the TestResult.
func (TestResult) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Int64IdMixin{},
	}
}
