// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: pkg/proto/configuration/archive/archive.proto

package archive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobArchiverConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Backend:
	//
	//	*BlobArchiverConfiguration_Local
	Backend isBlobArchiverConfiguration_Backend `protobuf_oneof:"backend"`
}

func (x *BlobArchiverConfiguration) Reset() {
	*x = BlobArchiverConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_configuration_archive_archive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobArchiverConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobArchiverConfiguration) ProtoMessage() {}

func (x *BlobArchiverConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_archive_archive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobArchiverConfiguration.ProtoReflect.Descriptor instead.
func (*BlobArchiverConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_archive_archive_proto_rawDescGZIP(), []int{0}
}

func (m *BlobArchiverConfiguration) GetBackend() isBlobArchiverConfiguration_Backend {
	if m != nil {
		return m.Backend
	}
	return nil
}

func (x *BlobArchiverConfiguration) GetLocal() *LocalFileArchiverConfiguration {
	if x, ok := x.GetBackend().(*BlobArchiverConfiguration_Local); ok {
		return x.Local
	}
	return nil
}

type isBlobArchiverConfiguration_Backend interface {
	isBlobArchiverConfiguration_Backend()
}

type BlobArchiverConfiguration_Local struct {
	Local *LocalFileArchiverConfiguration `protobuf:"bytes,1,opt,name=local,proto3,oneof"`
}

func (*BlobArchiverConfiguration_Local) isBlobArchiverConfiguration_Backend() {}

type LocalFileArchiverConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
}

func (x *LocalFileArchiverConfiguration) Reset() {
	*x = LocalFileArchiverConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_configuration_archive_archive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalFileArchiverConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFileArchiverConfiguration) ProtoMessage() {}

func (x *LocalFileArchiverConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_archive_archive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFileArchiverConfiguration.ProtoReflect.Descriptor instead.
func (*LocalFileArchiverConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_archive_archive_proto_rawDescGZIP(), []int{1}
}

func (x *LocalFileArchiverConfiguration) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

var File_pkg_proto_configuration_archive_archive_proto protoreflect.FileDescriptor

var file_pkg_proto_configuration_archive_archive_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x22, 0x7f, 0x0a, 0x19, 0x42, 0x6c, 0x6f, 0x62, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x57, 0x0a,
	0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x22, 0x3e, 0x0a, 0x1e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_configuration_archive_archive_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_archive_archive_proto_rawDescData = file_pkg_proto_configuration_archive_archive_proto_rawDesc
)

func file_pkg_proto_configuration_archive_archive_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_archive_archive_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_archive_archive_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_configuration_archive_archive_proto_rawDescData)
	})
	return file_pkg_proto_configuration_archive_archive_proto_rawDescData
}

var file_pkg_proto_configuration_archive_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_configuration_archive_archive_proto_goTypes = []any{
	(*BlobArchiverConfiguration)(nil),      // 0: buildbarn.configuration.archive.BlobArchiverConfiguration
	(*LocalFileArchiverConfiguration)(nil), // 1: buildbarn.configuration.archive.LocalFileArchiverConfiguration
}
var file_pkg_proto_configuration_archive_archive_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.archive.BlobArchiverConfiguration.local:type_name -> buildbarn.configuration.archive.LocalFileArchiverConfiguration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_archive_archive_proto_init() }
func file_pkg_proto_configuration_archive_archive_proto_init() {
	if File_pkg_proto_configuration_archive_archive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_configuration_archive_archive_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BlobArchiverConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_configuration_archive_archive_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LocalFileArchiverConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_configuration_archive_archive_proto_msgTypes[0].OneofWrappers = []any{
		(*BlobArchiverConfiguration_Local)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_configuration_archive_archive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_archive_archive_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_archive_archive_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_archive_archive_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_archive_archive_proto = out.File
	file_pkg_proto_configuration_archive_archive_proto_rawDesc = nil
	file_pkg_proto_configuration_archive_archive_proto_goTypes = nil
	file_pkg_proto_configuration_archive_archive_proto_depIdxs = nil
}
