// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.1
// source: github.com/buildbarn/bb-portal/pkg/proto/configuration/bb_seed/bb_seed.proto

package bb_seed

import (
	bb_portal "github.com/buildbarn/bb-portal/pkg/proto/configuration/bb_portal"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Database               *bb_portal.Database    `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Global                 *global.Configuration  `protobuf:"bytes,2,opt,name=global,proto3" json:"global,omitempty"`
	Instances              int32                  `protobuf:"varint,3,opt,name=instances,proto3" json:"instances,omitempty"`
	Users                  int32                  `protobuf:"varint,4,opt,name=users,proto3" json:"users,omitempty"`
	InvocationsPerInstance int32                  `protobuf:"varint,5,opt,name=invocations_per_instance,json=invocationsPerInstance,proto3" json:"invocations_per_instance,omitempty"`
	TargetsPerInvocation   int32                  `protobuf:"varint,6,opt,name=targets_per_invocation,json=targetsPerInvocation,proto3" json:"targets_per_invocation,omitempty"`
	TimeSpan               *durationpb.Duration   `protobuf:"bytes,7,opt,name=time_span,json=timeSpan,proto3" json:"time_span,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetDatabase() *bb_portal.Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *ApplicationConfiguration) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *ApplicationConfiguration) GetInvocationsPerInstance() int32 {
	if x != nil {
		return x.InvocationsPerInstance
	}
	return 0
}

func (x *ApplicationConfiguration) GetTargetsPerInvocation() int32 {
	if x != nil {
		return x.TargetsPerInvocation
	}
	return 0
}

func (x *ApplicationConfiguration) GetTimeSpan() *durationpb.Duration {
	if x != nil {
		return x.TimeSpan
	}
	return nil
}

var File_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDesc = "" +
	"\n" +
	"Lgithub.com/buildbarn/bb-portal/pkg/proto/configuration/bb_seed/bb_seed.proto\x12\x1fbuildbarn.configuration.bb_seed\x1a\x1egoogle/protobuf/duration.proto\x1aPgithub.com/buildbarn/bb-portal/pkg/proto/configuration/bb_portal/bb_portal.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\"\x86\x03\n" +
	"\x18ApplicationConfiguration\x12G\n" +
	"\bdatabase\x18\x01 \x01(\v2+.buildbarn.configuration.bb_portal.DatabaseR\bdatabase\x12E\n" +
	"\x06global\x18\x02 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12\x1c\n" +
	"\tinstances\x18\x03 \x01(\x05R\tinstances\x12\x14\n" +
	"\x05users\x18\x04 \x01(\x05R\x05users\x128\n" +
	"\x18invocations_per_instance\x18\x05 \x01(\x05R\x16invocationsPerInstance\x124\n" +
	"\x16targets_per_invocation\x18\x06 \x01(\x05R\x14targetsPerInvocation\x126\n" +
	"\ttime_span\x18\a \x01(\v2\x19.google.protobuf.DurationR\btimeSpanB@Z>github.com/buildbarn/bb-portal/pkg/proto/configuration/bb_seedb\x06proto3"

var (
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDesc), len(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDescData
}

var file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil), // 0: buildbarn.configuration.bb_seed.ApplicationConfiguration
	(*bb_portal.Database)(nil),       // 1: buildbarn.configuration.bb_portal.Database
	(*global.Configuration)(nil),     // 2: buildbarn.configuration.global.Configuration
	(*durationpb.Duration)(nil),      // 3: google.protobuf.Duration
}
var file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.bb_seed.ApplicationConfiguration.database:type_name -> buildbarn.configuration.bb_portal.Database
	2, // 1: buildbarn.configuration.bb_seed.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	3, // 2: buildbarn.configuration.bb_seed.ApplicationConfiguration.time_span:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_init() }
func file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_init() {
	if File_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDesc), len(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto = out.File
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_goTypes = nil
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_seed_bb_seed_proto_depIdxs = nil
}
