// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authenticated_users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuthenticatedUser = `-- name: CreateAuthenticatedUser :one
WITH new_row AS (
    INSERT INTO authenticated_users (
        user_uuid,
        external_id,
        display_name,
        user_info
    )
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (external_id) DO UPDATE SET
        display_name = COALESCE($3, authenticated_users.display_name),
        user_info = COALESCE($4, authenticated_users.user_info)
    RETURNING id, (xmax = 0) AS created
)
SELECT id, created FROM new_row
`

type CreateAuthenticatedUserParams struct {
	UserUuid    uuid.UUID
	ExternalID  string
	DisplayName sql.NullString
	UserInfo    pqtype.NullRawMessage
}

type CreateAuthenticatedUserRow struct {
	ID      int64
	Created bool
}

// A function for creating authenticated
// users. It returns the ID and a bool
// `created`: `true` if the user was
// created, `false` if the user already
// existed. The query uses the system column
// `xmax`, see docs for more information.
func (q *Queries) CreateAuthenticatedUser(ctx context.Context, arg CreateAuthenticatedUserParams) (CreateAuthenticatedUserRow, error) {
	row := q.db.QueryRowContext(ctx, createAuthenticatedUser,
		arg.UserUuid,
		arg.ExternalID,
		arg.DisplayName,
		arg.UserInfo,
	)
	var i CreateAuthenticatedUserRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
