// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builds.sql

package sqlc

import (
	"context"
)

const updateBuildTimestampFromInvocation = `-- name: UpdateBuildTimestampFromInvocation :exec
UPDATE builds
SET timestamp = bi.started_at
FROM bazel_invocations bi
WHERE bi.id = $1
  AND builds.id = bi.build_invocations
  AND bi.started_at < builds.timestamp
`

func (q *Queries) UpdateBuildTimestampFromInvocation(ctx context.Context, invocationID int64) error {
	_, err := q.db.ExecContext(ctx, updateBuildTimestampFromInvocation, invocationID)
	return err
}
