// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_metadata.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createEventMetadataBulk = `-- name: CreateEventMetadataBulk :exec
INSERT INTO event_metadata (
    bazel_invocation_id,
    event_hash,
    event_received_at,
    sequence_number
)
SELECT 
    $1,
    event_hash,
    event_received_at,
    sequence_number
FROM (
    SELECT 
        unnest($2::bytea[]) AS event_hash,
        unnest($3::timestamptz[]) AS event_received_at,
        unnest($4::bigint[]) AS sequence_number
) AS input
`

type CreateEventMetadataBulkParams struct {
	BazelInvocationID int64
	EventHashes       [][]byte
	EventReceivedAts  []time.Time
	SequenceNumbers   []int64
}

func (q *Queries) CreateEventMetadataBulk(ctx context.Context, arg CreateEventMetadataBulkParams) error {
	_, err := q.db.ExecContext(ctx, createEventMetadataBulk,
		arg.BazelInvocationID,
		pq.Array(arg.EventHashes),
		pq.Array(arg.EventReceivedAts),
		pq.Array(arg.SequenceNumbers),
	)
	return err
}

const recordEventMetadata = `-- name: RecordEventMetadata :execresult
INSERT INTO event_metadata (
    sequence_number,
    event_received_at,
    event_hash,
    bazel_invocation_id
)
SELECT 
    $1,
    $2,
    $3,
    b.id
FROM bazel_invocations AS b
WHERE b.invocation_id = $4
  AND b.bep_completed = FALSE
`

type RecordEventMetadataParams struct {
	SequenceNumber  int64
	EventReceivedAt time.Time
	EventHash       []byte
	InvocationID    uuid.UUID
}

func (q *Queries) RecordEventMetadata(ctx context.Context, arg RecordEventMetadataParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recordEventMetadata,
		arg.SequenceNumber,
		arg.EventReceivedAt,
		arg.EventHash,
		arg.InvocationID,
	)
}
