// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_metadata.sql

package sqlc

import (
	"context"
	"time"
)

const getOrCreateEventMetadata = `-- name: GetOrCreateEventMetadata :one
WITH new_row AS (
    INSERT INTO event_metadata (
        bazel_invocation_id,
        handled,
        event_received_at,
        version
    ) VALUES (
        $1, '\x', NOW(), 0
    )
    ON CONFLICT (bazel_invocation_id) DO NOTHING
    RETURNING id, handled, event_received_at, version
)
SELECT id, handled, event_received_at, version FROM new_row
UNION ALL
SELECT id, handled, event_received_at, version
FROM event_metadata
WHERE bazel_invocation_id = $1
`

type GetOrCreateEventMetadataRow struct {
	ID              int64
	Handled         []byte
	EventReceivedAt time.Time
	Version         int64
}

func (q *Queries) GetOrCreateEventMetadata(ctx context.Context, bazelInvocationID int64) (GetOrCreateEventMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateEventMetadata, bazelInvocationID)
	var i GetOrCreateEventMetadataRow
	err := row.Scan(
		&i.ID,
		&i.Handled,
		&i.EventReceivedAt,
		&i.Version,
	)
	return i, err
}

const updateEventMetadata = `-- name: UpdateEventMetadata :one
UPDATE event_metadata
SET 
    handled = $1,
    event_received_at = $2,
    version = version + 1
WHERE 
    id = $3
    AND version = $4
RETURNING version
`

type UpdateEventMetadataParams struct {
	Handled         []byte
	EventReceivedAt time.Time
	ID              int64
	Version         int64
}

func (q *Queries) UpdateEventMetadata(ctx context.Context, arg UpdateEventMetadataParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateEventMetadata,
		arg.Handled,
		arg.EventReceivedAt,
		arg.ID,
		arg.Version,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
