// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_metadata.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const recordEventMetadata = `-- name: RecordEventMetadata :execresult
INSERT INTO event_metadata (
    sequence_number,
    event_received_at,
    event_hash,
    bazel_invocation_id
)
SELECT 
    $1,
    $2,
    $3,
    b.id
FROM bazel_invocations AS b
WHERE b.invocation_id = $4
  AND b.bep_completed = FALSE
`

type RecordEventMetadataParams struct {
	SequenceNumber  int64
	EventReceivedAt time.Time
	EventHash       string
	InvocationID    uuid.UUID
}

func (q *Queries) RecordEventMetadata(ctx context.Context, arg RecordEventMetadataParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recordEventMetadata,
		arg.SequenceNumber,
		arg.EventReceivedAt,
		arg.EventHash,
		arg.InvocationID,
	)
}
