// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incomplete_artifacts.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createIncompleteArtifactGraphs = `-- name: CreateIncompleteArtifactGraphs :exec
INSERT INTO incomplete_artifact_graphs (
    bazel_invocation_id,
    seq_id,
    event
)
SELECT
    $1,
    seq_id,
    event
FROM (
    SELECT
        unnest($2::int[]) AS seq_id,
        unnest($3::bytea[]) AS event
) AS input
`

type CreateIncompleteArtifactGraphsParams struct {
	BazelInvocationID int64
	SeqIds            []int32
	Events            [][]byte
}

// Bulk-insert serialized BuildEvents (NamedSetOfFiles / TargetCompleted)
// into the artifact-graph staging table as they stream in.
func (q *Queries) CreateIncompleteArtifactGraphs(ctx context.Context, arg CreateIncompleteArtifactGraphsParams) error {
	_, err := q.db.ExecContext(ctx, createIncompleteArtifactGraphs, arg.BazelInvocationID, pq.Array(arg.SeqIds), pq.Array(arg.Events))
	return err
}

const deleteIncompleteArtifactGraphsFromPages = `-- name: DeleteIncompleteArtifactGraphsFromPages :execrows
DELETE FROM incomplete_artifact_graphs g
USING bazel_invocations AS i
WHERE
    g.bazel_invocation_id = i.id
    AND g.ctid >= format('(%s,0)', $1::bigint)::tid
    AND g.ctid < format('(%s,0)', $1::bigint + $2::bigint)::tid
    AND i.bep_completed = true
    AND EXISTS (
        SELECT 1 FROM invocation_artifact_graphs a
        WHERE a.bazel_invocation_id = i.id
    )
`

type DeleteIncompleteArtifactGraphsFromPagesParams struct {
	FromPage int64
	Pages    int64
}

// Delete staged events for invocations whose graph has already been
// compacted into invocation_artifact_graphs. Paged via ctid so cleanup is
// spread across cleanup ticks via nextSlice(), mirroring
// DeleteIncompleteLogsFromPages.
func (q *Queries) DeleteIncompleteArtifactGraphsFromPages(ctx context.Context, arg DeleteIncompleteArtifactGraphsFromPagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIncompleteArtifactGraphsFromPages, arg.FromPage, arg.Pages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIncompleteArtifactGraphEvents = `-- name: GetIncompleteArtifactGraphEvents :many
SELECT event
FROM incomplete_artifact_graphs
WHERE bazel_invocation_id = $1
ORDER BY seq_id
`

// Read all staged artifact-graph events for an invocation, in arrival
// order. Used both for compaction and for serving the graph in its
// partial state before compaction has run.
func (q *Queries) GetIncompleteArtifactGraphEvents(ctx context.Context, bazelInvocationID int64) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, getIncompleteArtifactGraphEvents, bazelInvocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event []byte
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
