// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incomplete_build_logs.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createIncompleteBuildLogs = `-- name: CreateIncompleteBuildLogs :exec
INSERT INTO incomplete_build_logs (
    bazel_invocation_id,
    snippet_id,
    log_snippet
)
SELECT 
    $1,
    snippet_id,
    log_snippet
FROM (
    SELECT 
        unnest($2::int[]) AS snippet_id,
        unnest($3::bytea[]) AS log_snippet
) AS input
`

type CreateIncompleteBuildLogsParams struct {
	BazelInvocationID int64
	SnippetIds        []int32
	LogSnippets       [][]byte
}

func (q *Queries) CreateIncompleteBuildLogs(ctx context.Context, arg CreateIncompleteBuildLogsParams) error {
	_, err := q.db.ExecContext(ctx, createIncompleteBuildLogs, arg.BazelInvocationID, pq.Array(arg.SnippetIds), pq.Array(arg.LogSnippets))
	return err
}

const deleteIncompleteLogsFromPages = `-- name: DeleteIncompleteLogsFromPages :execrows
DELETE FROM incomplete_build_logs l
USING bazel_invocations AS i
WHERE
    l.bazel_invocation_id = i.id
    AND l.ctid >= format('(%s,0)', $1::bigint)::tid
    AND l.ctid < format('(%s,0)', $1::bigint + $2::bigint)::tid
    AND i.bep_completed = true
    AND EXISTS (
        SELECT 1 FROM build_log_chunks c
        WHERE c.bazel_invocation_build_log_chunks = i.id
    )
`

type DeleteIncompleteLogsFromPagesParams struct {
	FromPage int64
	Pages    int64
}

func (q *Queries) DeleteIncompleteLogsFromPages(ctx context.Context, arg DeleteIncompleteLogsFromPagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIncompleteLogsFromPages, arg.FromPage, arg.Pages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
