// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incomplete_build_logs.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createIncompleteBuildLogs = `-- name: CreateIncompleteBuildLogs :exec
INSERT INTO incomplete_build_logs (
    bazel_invocation_id,
    snippet_id,
    log_snippet
)
SELECT 
    $1,
    snippet_id,
    log_snippet
FROM (
    SELECT 
        unnest($2::int[]) AS snippet_id,
        unnest($3::text[]) AS log_snippet
) AS input
`

type CreateIncompleteBuildLogsParams struct {
	BazelInvocationID int64
	SnippetIds        []int32
	LogSnippets       []string
}

func (q *Queries) CreateIncompleteBuildLogs(ctx context.Context, arg CreateIncompleteBuildLogsParams) error {
	_, err := q.db.ExecContext(ctx, createIncompleteBuildLogs, arg.BazelInvocationID, pq.Array(arg.SnippetIds), pq.Array(arg.LogSnippets))
	return err
}
