// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_names.sql

package sqlc

import (
	"context"
)

const createInstanceName = `-- name: CreateInstanceName :one
WITH new_row AS (
    INSERT INTO instance_names (name) VALUES ($1)
    ON CONFLICT (name) DO NOTHING
    RETURNING id
)
SELECT id FROM new_row
UNION ALL
SELECT id FROM instance_names WHERE name = $1
LIMIT 1
`

// An idempotent function for creating an instance name. If the instance
// name already exists, it will return the existing id.
func (q *Queries) CreateInstanceName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createInstanceName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
