// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invocation_artifacts.sql

package sqlc

import (
	"context"
	"time"
)

const deleteOldInvocationArtifactGraphsFromPages = `-- name: DeleteOldInvocationArtifactGraphsFromPages :execrows
DELETE FROM invocation_artifact_graphs
WHERE
    ctid >= format('(%s,0)', $1::bigint)::tid
    AND ctid < format('(%s,0)', $1::bigint + $2::bigint)::tid
    AND bazel_invocation_id IN (
      SELECT id FROM bazel_invocations
      WHERE bep_completed = true
        AND ended_at IS NOT NULL
        AND ended_at < $3::timestamptz
    )
`

type DeleteOldInvocationArtifactGraphsFromPagesParams struct {
	FromPage   int64
	Pages      int64
	CutoffTime time.Time
}

// Delete artifact-graph rows whose owning invocation completed more than
// artifact_retention ago. Paged via ctid on the artifact graphs table —
// same pattern as DeleteOldInvocationsFromPages so cleanup is evenly
// spread across cleanup ticks via nextSlice().
func (q *Queries) DeleteOldInvocationArtifactGraphsFromPages(ctx context.Context, arg DeleteOldInvocationArtifactGraphsFromPagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldInvocationArtifactGraphsFromPages, arg.FromPage, arg.Pages, arg.CutoffTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInvocationArtifactGraph = `-- name: GetInvocationArtifactGraph :one
SELECT payload
FROM invocation_artifact_graphs
WHERE bazel_invocation_id = $1
`

func (q *Queries) GetInvocationArtifactGraph(ctx context.Context, bazelInvocationID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getInvocationArtifactGraph, bazelInvocationID)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const insertInvocationArtifactGraph = `-- name: InsertInvocationArtifactGraph :exec
INSERT INTO invocation_artifact_graphs (
    payload,
    bazel_invocation_id
) VALUES (
    $1::bytea,
    $2::bigint
)
ON CONFLICT (bazel_invocation_id) DO UPDATE SET
    payload = EXCLUDED.payload
`

type InsertInvocationArtifactGraphParams struct {
	Payload           []byte
	BazelInvocationID int64
}

// Insert (or replace) the compressed artifact graph for an invocation.
// Idempotent via the unique foreign key on bazel_invocation_id.
func (q *Queries) InsertInvocationArtifactGraph(ctx context.Context, arg InsertInvocationArtifactGraphParams) error {
	_, err := q.db.ExecContext(ctx, insertInvocationArtifactGraph, arg.Payload, arg.BazelInvocationID)
	return err
}
