// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invocation_artifacts.sql

package sqlc

import (
	"context"
	"time"
)

const deleteOldInvocationArtifactGraphsFromPages = `-- name: DeleteOldInvocationArtifactGraphsFromPages :execrows
DELETE FROM invocation_artifact_graphs
WHERE
    ctid >= format('(%s,0)', $1::bigint)::tid
    AND ctid < format('(%s,0)', $1::bigint + $2::bigint)::tid
    AND bazel_invocation_artifact_graph IN (
      SELECT id FROM bazel_invocations
      WHERE bep_completed = true
        AND ended_at IS NOT NULL
        AND ended_at < $3::timestamptz
    )
`

type DeleteOldInvocationArtifactGraphsFromPagesParams struct {
	FromPage   int64
	Pages      int64
	CutoffTime time.Time
}

// Delete artifact-graph rows whose owning invocation completed more than
// artifact_retention ago. Paged via ctid on the artifact graphs table —
// same pattern as DeleteOldInvocationsFromPages so cleanup is evenly
// spread across cleanup ticks via nextSlice().
func (q *Queries) DeleteOldInvocationArtifactGraphsFromPages(ctx context.Context, arg DeleteOldInvocationArtifactGraphsFromPagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldInvocationArtifactGraphsFromPages, arg.FromPage, arg.Pages, arg.CutoffTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInvocationArtifactGraph = `-- name: GetInvocationArtifactGraph :one
SELECT payload, uncompressed_size
FROM invocation_artifact_graphs
WHERE bazel_invocation_artifact_graph = $1
`

type GetInvocationArtifactGraphRow struct {
	Payload          []byte
	UncompressedSize int64
}

func (q *Queries) GetInvocationArtifactGraph(ctx context.Context, bazelInvocationID int64) (GetInvocationArtifactGraphRow, error) {
	row := q.db.QueryRowContext(ctx, getInvocationArtifactGraph, bazelInvocationID)
	var i GetInvocationArtifactGraphRow
	err := row.Scan(&i.Payload, &i.UncompressedSize)
	return i, err
}

const insertInvocationArtifactGraph = `-- name: InsertInvocationArtifactGraph :exec
INSERT INTO invocation_artifact_graphs (
    payload,
    uncompressed_size,
    bazel_invocation_artifact_graph
) VALUES (
    $1::bytea,
    $2::bigint,
    $3::bigint
)
ON CONFLICT (bazel_invocation_artifact_graph) DO UPDATE SET
    payload = EXCLUDED.payload,
    uncompressed_size = EXCLUDED.uncompressed_size
`

type InsertInvocationArtifactGraphParams struct {
	Payload           []byte
	UncompressedSize  int64
	BazelInvocationID int64
}

// Insert (or replace) the compressed artifact graph for an invocation.
// Idempotent via the unique edge on bazel_invocation_artifact_graph.
func (q *Queries) InsertInvocationArtifactGraph(ctx context.Context, arg InsertInvocationArtifactGraphParams) error {
	_, err := q.db.ExecContext(ctx, insertInvocationArtifactGraph, arg.Payload, arg.UncompressedSize, arg.BazelInvocationID)
	return err
}
