// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invocation_targets.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createInvocationTargetsBulk = `-- name: CreateInvocationTargetsBulk :exec
INSERT INTO invocation_targets (
    bazel_invocation_invocation_targets,
    target_invocation_targets,
    success,
    tags,
    start_time_in_ms,
    end_time_in_ms,
    duration_in_ms,
    failure_message,
    abort_reason
)
SELECT
    $1,
    target_id,
    success,
    NULLIF(tags, '')::jsonb,
    NULLIF(start_time, 0),
    NULLIF(end_time, 0),
    NULLIF(duration, 0),
    NULLIF(failure_message, ''),
    abort_reason
FROM (
    SELECT 
        unnest($2::bigint[]) AS target_id,
        unnest($3::boolean[]) AS success,
        unnest($4::text[]) AS tags,
        unnest($5::bigint[]) AS start_time,
        unnest($6::bigint[]) AS end_time,
        unnest($7::bigint[]) AS duration,
        unnest($8::text[]) AS failure_message,
        unnest($9::text[]) AS abort_reason
) AS input
`

type CreateInvocationTargetsBulkParams struct {
	BazelInvocationID int64
	TargetIds         []int64
	Successes         []bool
	TagsList          []string
	StartTimes        []int64
	EndTimes          []int64
	Durations         []int64
	FailureMessages   []string
	AbortReasons      []string
}

func (q *Queries) CreateInvocationTargetsBulk(ctx context.Context, arg CreateInvocationTargetsBulkParams) error {
	_, err := q.db.ExecContext(ctx, createInvocationTargetsBulk,
		arg.BazelInvocationID,
		pq.Array(arg.TargetIds),
		pq.Array(arg.Successes),
		pq.Array(arg.TagsList),
		pq.Array(arg.StartTimes),
		pq.Array(arg.EndTimes),
		pq.Array(arg.Durations),
		pq.Array(arg.FailureMessages),
		pq.Array(arg.AbortReasons),
	)
	return err
}
