// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invocation_targets.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createInvocationTargetsBulk = `-- name: CreateInvocationTargetsBulk :exec
INSERT INTO invocation_targets (
    bazel_invocation_invocation_targets,
    target_invocation_targets,
    invocation_target_configuration,
    success,
    tags,
    failure_message,
    abort_reason
)
SELECT
    $1,
    input.target_id,
    cfg.id,
    input.success,
    NULLIF(input.tags, '')::jsonb,
    NULLIF(input.failure_message, ''),
    input.abort_reason
FROM (
    SELECT
        unnest($2::bigint[]) AS target_id,
        unnest($3::text[]) AS configuration_external_id,
        unnest($4::boolean[]) AS success,
        unnest($5::text[]) AS tags,
        unnest($6::text[]) AS failure_message,
        unnest($7::text[]) AS abort_reason
) AS input
JOIN configurations cfg
  ON cfg.bazel_invocation_id = $1
  AND cfg.configuration_id = input.configuration_external_id
`

type CreateInvocationTargetsBulkParams struct {
	BazelInvocationID int64
	TargetIds         []int64
	ConfigurationIds  []string
	Successes         []bool
	TagsList          []string
	FailureMessages   []string
	AbortReasons      []string
}

func (q *Queries) CreateInvocationTargetsBulk(ctx context.Context, arg CreateInvocationTargetsBulkParams) error {
	_, err := q.db.ExecContext(ctx, createInvocationTargetsBulk,
		arg.BazelInvocationID,
		pq.Array(arg.TargetIds),
		pq.Array(arg.ConfigurationIds),
		pq.Array(arg.Successes),
		pq.Array(arg.TagsList),
		pq.Array(arg.FailureMessages),
		pq.Array(arg.AbortReasons),
	)
	return err
}
