// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invocation_targets.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createInvocationTargetsBulk = `-- name: CreateInvocationTargetsBulk :exec
INSERT INTO invocation_targets (
    bazel_invocation_invocation_targets,
    target_invocation_targets,
    invocation_target_configuration,
    success,
    tags,
    start_time_in_ms,
    end_time_in_ms,
    duration_in_ms,
    failure_message,
    abort_reason
)
SELECT
    $1,
    input.target_id,
    cfg.id,
    input.success,
    NULLIF(input.tags, '')::jsonb,
    NULLIF(input.start_time, 0),
    NULLIF(input.end_time, 0),
    NULLIF(input.duration, 0),
    NULLIF(input.failure_message, ''),
    input.abort_reason
FROM (
    SELECT
        unnest($2::bigint[]) AS target_id,
        unnest($3::text[]) AS configuration_external_id,
        unnest($4::boolean[]) AS success,
        unnest($5::text[]) AS tags,
        unnest($6::bigint[]) AS start_time,
        unnest($7::bigint[]) AS end_time,
        unnest($8::bigint[]) AS duration,
        unnest($9::text[]) AS failure_message,
        unnest($10::text[]) AS abort_reason
) AS input
JOIN configurations cfg
  ON cfg.bazel_invocation_id = $1
  AND cfg.configuration_id = input.configuration_external_id
`

type CreateInvocationTargetsBulkParams struct {
	BazelInvocationID int64
	TargetIds         []int64
	ConfigurationIds  []string
	Successes         []bool
	TagsList          []string
	StartTimes        []int64
	EndTimes          []int64
	Durations         []int64
	FailureMessages   []string
	AbortReasons      []string
}

func (q *Queries) CreateInvocationTargetsBulk(ctx context.Context, arg CreateInvocationTargetsBulkParams) error {
	_, err := q.db.ExecContext(ctx, createInvocationTargetsBulk,
		arg.BazelInvocationID,
		pq.Array(arg.TargetIds),
		pq.Array(arg.ConfigurationIds),
		pq.Array(arg.Successes),
		pq.Array(arg.TagsList),
		pq.Array(arg.StartTimes),
		pq.Array(arg.EndTimes),
		pq.Array(arg.Durations),
		pq.Array(arg.FailureMessages),
		pq.Array(arg.AbortReasons),
	)
	return err
}

const getInvocationTargetIDsForBatch = `-- name: GetInvocationTargetIDsForBatch :many
SELECT id, target_invocation_targets AS target_id
FROM invocation_targets
WHERE bazel_invocation_invocation_targets = $1
  AND target_invocation_targets = ANY($2::bigint[])
`

type GetInvocationTargetIDsForBatchParams struct {
	BazelInvocationID int64
	TargetIds         []int64
}

type GetInvocationTargetIDsForBatchRow struct {
	ID       int64
	TargetID int64
}

func (q *Queries) GetInvocationTargetIDsForBatch(ctx context.Context, arg GetInvocationTargetIDsForBatchParams) ([]GetInvocationTargetIDsForBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvocationTargetIDsForBatch, arg.BazelInvocationID, pq.Array(arg.TargetIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvocationTargetIDsForBatchRow
	for rows.Next() {
		var i GetInvocationTargetIDsForBatchRow
		if err := rows.Scan(&i.ID, &i.TargetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
