// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActionCacheStatistic struct {
	ID                                 int64
	SizeInBytes                        sql.NullInt64
	SaveTimeInMs                       sql.NullInt64
	LoadTimeInMs                       sql.NullInt64
	Hits                               sql.NullInt32
	Misses                             sql.NullInt32
	ActionSummaryActionCacheStatistics sql.NullInt64
}

type ActionDatum struct {
	ID                      int64
	Mnemonic                sql.NullString
	ActionsExecuted         sql.NullInt64
	ActionsCreated          sql.NullInt64
	FirstStartedMs          sql.NullInt64
	LastEndedMs             sql.NullInt64
	SystemTime              sql.NullInt64
	UserTime                sql.NullInt64
	ActionSummaryActionData sql.NullInt64
}

type ActionSummary struct {
	ID                                int64
	ActionsCreated                    sql.NullInt64
	ActionsCreatedNotIncludingAspects sql.NullInt64
	ActionsExecuted                   sql.NullInt64
	RemoteCacheHits                   sql.NullInt64
	MetricsActionSummary              sql.NullInt64
}

type ArtifactMetric struct {
	ID                                        int64
	SourceArtifactsReadSizeInBytes            sql.NullInt64
	SourceArtifactsReadCount                  sql.NullInt32
	OutputArtifactsSeenSizeInBytes            sql.NullInt64
	OutputArtifactsSeenCount                  sql.NullInt32
	OutputArtifactsFromActionCacheSizeInBytes sql.NullInt64
	OutputArtifactsFromActionCacheCount       sql.NullInt32
	TopLevelArtifactsSizeInBytes              sql.NullInt64
	TopLevelArtifactsCount                    sql.NullInt32
	MetricsArtifactMetrics                    sql.NullInt64
}

type AuthenticatedUser struct {
	ID          int64
	UserUuid    uuid.UUID
	ExternalID  string
	DisplayName sql.NullString
	UserInfo    pqtype.NullRawMessage
}

type BazelInvocation struct {
	ID                                  int64
	InvocationID                        uuid.UUID
	StartedAt                           sql.NullTime
	EndedAt                             sql.NullTime
	ChangeNumber                        sql.NullInt64
	PatchsetNumber                      sql.NullInt64
	BepCompleted                        bool
	StepLabel                           sql.NullString
	UserEmail                           sql.NullString
	UserLdap                            sql.NullString
	Cpu                                 sql.NullString
	PlatformName                        sql.NullString
	Hostname                            sql.NullString
	IsCiWorker                          sql.NullBool
	ConfigurationMnemonic               sql.NullString
	NumFetches                          sql.NullInt64
	ProfileName                         sql.NullString
	BazelVersion                        sql.NullString
	ExitCodeName                        sql.NullString
	ExitCodeCode                        sql.NullInt32
	CommandLineCommand                  sql.NullString
	CommandLineExecutable               sql.NullString
	CommandLineResidual                 sql.NullString
	CommandLine                         pqtype.NullRawMessage
	ExplicitCommandLine                 pqtype.NullRawMessage
	StartupOptions                      pqtype.NullRawMessage
	ExplicitStartupOptions              pqtype.NullRawMessage
	ProcessedEventStarted               bool
	ProcessedEventBuildMetadata         bool
	ProcessedEventOptionsParsed         bool
	ProcessedEventBuildFinished         bool
	ProcessedEventStructuredCommandLine bool
	ProcessedEventWorkspaceStatus       bool
	AuthenticatedUserBazelInvocations   sql.NullInt64
	BuildInvocations                    sql.NullInt64
	InstanceNameBazelInvocations        int64
}

type BazelInvocationProblem struct {
	ID                      int64
	ProblemType             string
	Label                   string
	BepEvents               json.RawMessage
	BazelInvocationProblems sql.NullInt64
}

type Blob struct {
	ID                int64
	Uri               string
	SizeBytes         sql.NullInt64
	ArchivingStatus   string
	Reason            sql.NullString
	ArchiveUrl        sql.NullString
	InstanceNameBlobs int64
}

type Build struct {
	ID                 int64
	BuildUrl           string
	BuildUuid          uuid.UUID
	Timestamp          time.Time
	InstanceNameBuilds int64
}

type BuildGraphMetric struct {
	ID                                        int64
	ActionLookupValueCount                    sql.NullInt32
	ActionLookupValueCountNotIncludingAspects sql.NullInt32
	ActionCount                               sql.NullInt32
	ActionCountNotIncludingAspects            sql.NullInt32
	InputFileConfiguredTargetCount            sql.NullInt32
	OutputFileConfiguredTargetCount           sql.NullInt32
	OtherConfiguredTargetCount                sql.NullInt32
	OutputArtifactCount                       sql.NullInt32
	PostInvocationSkyframeNodeCount           sql.NullInt32
	BuildGraphMetricsDirtiedValues            sql.NullInt64
	BuildGraphMetricsChangedValues            sql.NullInt64
	BuildGraphMetricsBuiltValues              sql.NullInt64
	BuildGraphMetricsCleanedValues            sql.NullInt64
	MetricsBuildGraphMetrics                  sql.NullInt64
}

type BuildLogChunk struct {
	ID                            int64
	Data                          []byte
	ChunkIndex                    int64
	FirstLineIndex                int64
	LastLineIndex                 int64
	BazelInvocationBuildLogChunks int64
}

type ConnectionMetadatum struct {
	ID                                int64
	ConnectionLastOpenAt              time.Time
	BazelInvocationConnectionMetadata int64
}

type CumulativeMetric struct {
	ID                       int64
	NumAnalyses              sql.NullInt32
	NumBuilds                sql.NullInt32
	MetricsCumulativeMetrics sql.NullInt64
}

type EvaluationStat struct {
	ID                               int64
	SkyfunctionName                  sql.NullString
	Count                            sql.NullInt64
	BuildGraphMetricsEvaluatedValues sql.NullInt64
}

type EventMetadatum struct {
	ID                int64
	SequenceNumber    int64
	EventReceivedAt   time.Time
	EventHash         []byte
	BazelInvocationID int64
}

type ExectionInfo struct {
	ID                         int64
	TimeoutSeconds             sql.NullInt32
	Strategy                   sql.NullString
	CachedRemotely             sql.NullBool
	ExitCode                   sql.NullInt32
	Hostname                   sql.NullString
	TestResultBesExecutionInfo sql.NullInt64
}

type GarbageMetric struct {
	ID                          int64
	Type                        sql.NullString
	GarbageCollected            sql.NullInt64
	MemoryMetricsGarbageMetrics sql.NullInt64
}

type IncompleteBuildLog struct {
	ID                int64
	SnippetID         int32
	LogSnippet        []byte
	BazelInvocationID int64
}

type InstanceName struct {
	ID   int64
	Name string
}

type InvocationFile struct {
	ID                             int64
	Name                           string
	Content                        sql.NullString
	Digest                         sql.NullString
	SizeBytes                      sql.NullInt64
	DigestFunction                 sql.NullString
	BazelInvocationInvocationFiles sql.NullInt64
}

type InvocationTarget struct {
	ID                               int64
	Success                          bool
	Tags                             pqtype.NullRawMessage
	StartTimeInMs                    sql.NullInt64
	EndTimeInMs                      sql.NullInt64
	DurationInMs                     sql.NullInt64
	FailureMessage                   sql.NullString
	AbortReason                      string
	BazelInvocationInvocationTargets int64
	TargetInvocationTargets          int64
}

type MemoryMetric struct {
	ID                             int64
	PeakPostGcHeapSize             sql.NullInt64
	UsedHeapSizePostBuild          sql.NullInt64
	PeakPostGcTenuredSpaceHeapSize sql.NullInt64
	MetricsMemoryMetrics           sql.NullInt64
}

type Metric struct {
	ID                     int64
	BazelInvocationMetrics sql.NullInt64
}

type MissDetail struct {
	ID                               int64
	Reason                           string
	Count                            sql.NullInt32
	ActionCacheStatisticsMissDetails sql.NullInt64
}

type NamedSetOfFile struct {
	ID                      int64
	NamedSetOfFilesFileSets sql.NullInt64
	OutputGroupFileSets     sql.NullInt64
}

type NetworkMetric struct {
	ID                    int64
	MetricsNetworkMetrics sql.NullInt64
}

type OutputGroup struct {
	ID         int64
	Name       sql.NullString
	Incomplete sql.NullBool
}

type PackageLoadMetric struct {
	ID                               int64
	Name                             sql.NullString
	LoadDuration                     sql.NullInt64
	NumTargets                       sql.NullInt64
	ComputationSteps                 sql.NullInt64
	NumTransitiveLoads               sql.NullInt64
	PackageOverhead                  sql.NullInt64
	PackageMetricsPackageLoadMetrics sql.NullInt64
}

type PackageMetric struct {
	ID                    int64
	PackagesLoaded        sql.NullInt64
	MetricsPackageMetrics sql.NullInt64
}

type ResourceUsage struct {
	ID                        int64
	Name                      sql.NullString
	Value                     sql.NullString
	ExectionInfoResourceUsage sql.NullInt64
}

type RunnerCount struct {
	ID                       int64
	Name                     sql.NullString
	ExecKind                 sql.NullString
	ActionsExecuted          sql.NullInt64
	ActionSummaryRunnerCount sql.NullInt64
}

type SourceControl struct {
	ID                           int64
	Provider                     sql.NullString
	InstanceUrl                  sql.NullString
	Repo                         sql.NullString
	Refs                         sql.NullString
	CommitSha                    sql.NullString
	Actor                        sql.NullString
	EventName                    sql.NullString
	Workflow                     sql.NullString
	RunID                        sql.NullString
	RunNumber                    sql.NullString
	Job                          sql.NullString
	Action                       sql.NullString
	RunnerName                   sql.NullString
	RunnerArch                   sql.NullString
	RunnerOs                     sql.NullString
	Workspace                    sql.NullString
	BazelInvocationSourceControl sql.NullInt64
}

type SystemNetworkStat struct {
	ID                               int64
	BytesSent                        sql.NullInt64
	BytesRecv                        sql.NullInt64
	PacketsSent                      sql.NullInt64
	PacketsRecv                      sql.NullInt64
	PeakBytesSentPerSec              sql.NullInt64
	PeakBytesRecvPerSec              sql.NullInt64
	PeakPacketsSentPerSec            sql.NullInt64
	PeakPacketsRecvPerSec            sql.NullInt64
	NetworkMetricsSystemNetworkStats sql.NullInt64
}

type Target struct {
	ID                  int64
	Label               string
	Aspect              string
	TargetKind          string
	InstanceNameTargets int64
}

type TargetKindMapping struct {
	ID                int64
	StartTimeInMs     sql.NullInt64
	BazelInvocationID int64
	TargetID          int64
}

type TargetMetric struct {
	ID                                   int64
	TargetsLoaded                        sql.NullInt64
	TargetsConfigured                    sql.NullInt64
	TargetsConfiguredNotIncludingAspects sql.NullInt64
	MetricsTargetMetrics                 sql.NullInt64
}

type TestCollection struct {
	ID                            int64
	Label                         sql.NullString
	OverallStatus                 sql.NullString
	Strategy                      sql.NullString
	CachedLocally                 sql.NullBool
	CachedRemotely                sql.NullBool
	FirstSeen                     sql.NullTime
	DurationMs                    sql.NullInt64
	BazelInvocationTestCollection sql.NullInt64
}

type TestFile struct {
	ID                            int64
	Digest                        sql.NullString
	File                          sql.NullString
	Length                        sql.NullInt64
	Name                          sql.NullString
	Prefix                        pqtype.NullRawMessage
	NamedSetOfFilesFiles          sql.NullInt64
	OutputGroupInlineFiles        sql.NullInt64
	TestResultBesTestActionOutput sql.NullInt64
	TestSummaryPassed             sql.NullInt64
	TestSummaryFailed             sql.NullInt64
}

type TestResultBeSs struct {
	ID                          int64
	TestStatus                  sql.NullString
	StatusDetails               sql.NullString
	Label                       sql.NullString
	Warning                     pqtype.NullRawMessage
	CachedLocally               sql.NullBool
	TestAttemptStartMillisEpoch sql.NullInt64
	TestAttemptStart            sql.NullString
	TestAttemptDurationMillis   sql.NullInt64
	TestAttemptDuration         sql.NullInt64
	TestCollectionTestResults   sql.NullInt64
}

type TestSummary struct {
	ID                        int64
	OverallStatus             sql.NullString
	TotalRunCount             sql.NullInt32
	RunCount                  sql.NullInt32
	AttemptCount              sql.NullInt32
	ShardCount                sql.NullInt32
	TotalNumCached            sql.NullInt32
	FirstStartTime            sql.NullInt64
	LastStopTime              sql.NullInt64
	TotalRunDuration          sql.NullInt64
	Label                     sql.NullString
	TestCollectionTestSummary sql.NullInt64
}

type TimingBreakdown struct {
	ID                          int64
	Name                        sql.NullString
	Time                        sql.NullString
	ExectionInfoTimingBreakdown sql.NullInt64
}

type TimingChild struct {
	ID                   int64
	Name                 sql.NullString
	Time                 sql.NullString
	TimingBreakdownChild sql.NullInt64
}

type TimingMetric struct {
	ID                        int64
	CpuTimeInMs               sql.NullInt64
	WallTimeInMs              sql.NullInt64
	AnalysisPhaseTimeInMs     sql.NullInt64
	ExecutionPhaseTimeInMs    sql.NullInt64
	ActionsExecutionStartInMs sql.NullInt64
	MetricsTimingMetrics      sql.NullInt64
}
