// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	RecordEventMetadata(ctx context.Context, arg RecordEventMetadataParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
