// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const createTargets = `-- name: CreateTargets :many
INSERT INTO targets (instance_name_targets, label, aspect, target_kind)
SELECT 
    instance_name_id, label, aspect, target_kind
FROM (
    SELECT 
        $1::bigint AS instance_name_id,
        unnest($2::text[]) AS label,
        unnest($3::text[]) AS aspect,
        unnest($4::text[]) AS target_kind
) AS input
ORDER BY
    label COLLATE "C",
    aspect COLLATE "C",
    target_kind COLLATE "C"
RETURNING id, label, aspect, target_kind
`

type CreateTargetsParams struct {
	InstanceNameID int64
	Labels         []string
	Aspects        []string
	TargetKinds    []string
}

type CreateTargetsRow struct {
	ID         int64
	Label      string
	Aspect     string
	TargetKind string
}

// ORDER BY here is enforcing an insertion order for two reasons:
//  1. Prevent concurrent requests from deadlocking each other in case
//
// they have overlapping insertions of targets in different orders.
//  2. Explicitly collate to normalize sort order between database
//
// instantiations, otherwise golden file generation may have a different
// order than what's used during the test.
func (q *Queries) CreateTargets(ctx context.Context, arg CreateTargetsParams) ([]CreateTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, createTargets,
		arg.InstanceNameID,
		pq.Array(arg.Labels),
		pq.Array(arg.Aspects),
		pq.Array(arg.TargetKinds),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateTargetsRow
	for rows.Next() {
		var i CreateTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Aspect,
			&i.TargetKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTargets = `-- name: FindTargets :many
SELECT t.id, t.label, t.aspect, t.target_kind
FROM (
    SELECT 
        $1::bigint AS instance_name_id,
        unnest($2::text[]) AS label,
        unnest($3::text[]) AS aspect,
        unnest($4::text[]) AS target_kind
) AS input
JOIN targets t ON 
    t.instance_name_targets = input.instance_name_id AND
    t.label = input.label AND
    t.aspect = input.aspect AND
    t.target_kind = input.target_kind
`

type FindTargetsParams struct {
	InstanceNameID int64
	Labels         []string
	Aspects        []string
	TargetKinds    []string
}

type FindTargetsRow struct {
	ID         int64
	Label      string
	Aspect     string
	TargetKind string
}

func (q *Queries) FindTargets(ctx context.Context, arg FindTargetsParams) ([]FindTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, findTargets,
		arg.InstanceNameID,
		pq.Array(arg.Labels),
		pq.Array(arg.Aspects),
		pq.Array(arg.TargetKinds),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTargetsRow
	for rows.Next() {
		var i FindTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Aspect,
			&i.TargetKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
