// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/buildbarn/bb-portal/pkg/proto/configuration/bb_portal/bb_portal.proto

package bb_portal

import (
	auth "github.com/buildbarn/bb-storage/pkg/proto/configuration/auth"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	server "github.com/buildbarn/bb-storage/pkg/proto/configuration/http/server"
	jmespath "github.com/buildbarn/bb-storage/pkg/proto/configuration/jmespath"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostgresSource struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionString string                 `protobuf:"bytes,1,opt,name=connection_string,json=connectionString,proto3" json:"connection_string,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostgresSource) Reset() {
	*x = PostgresSource{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresSource) ProtoMessage() {}

func (x *PostgresSource) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresSource.ProtoReflect.Descriptor instead.
func (*PostgresSource) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{0}
}

func (x *PostgresSource) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type Database struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*Database_Postgres
	Source                      isDatabase_Source                             `protobuf_oneof:"source"`
	ConnectionPoolConfiguration *Database_DatabaseConnectionPoolConfiguration `protobuf:"bytes,3,opt,name=connection_pool_configuration,json=connectionPoolConfiguration,proto3" json:"connection_pool_configuration,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{1}
}

func (x *Database) GetSource() isDatabase_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Database) GetPostgres() *PostgresSource {
	if x != nil {
		if x, ok := x.Source.(*Database_Postgres); ok {
			return x.Postgres
		}
	}
	return nil
}

func (x *Database) GetConnectionPoolConfiguration() *Database_DatabaseConnectionPoolConfiguration {
	if x != nil {
		return x.ConnectionPoolConfiguration
	}
	return nil
}

type isDatabase_Source interface {
	isDatabase_Source()
}

type Database_Postgres struct {
	Postgres *PostgresSource `protobuf:"bytes,2,opt,name=postgres,proto3,oneof"`
}

func (*Database_Postgres) isDatabase_Source() {}

type AuthMetadataExtractorConfiguration struct {
	state                                   protoimpl.MessageState `protogen:"open.v1"`
	ExternalIdExtractionJmespathExpression  *jmespath.Expression   `protobuf:"bytes,1,opt,name=external_id_extraction_jmespath_expression,json=externalIdExtractionJmespathExpression,proto3" json:"external_id_extraction_jmespath_expression,omitempty"`
	DisplayNameExtractionJmespathExpression *jmespath.Expression   `protobuf:"bytes,2,opt,name=display_name_extraction_jmespath_expression,json=displayNameExtractionJmespathExpression,proto3" json:"display_name_extraction_jmespath_expression,omitempty"`
	UserInfoExtractionJmespathExpression    *jmespath.Expression   `protobuf:"bytes,3,opt,name=user_info_extraction_jmespath_expression,json=userInfoExtractionJmespathExpression,proto3" json:"user_info_extraction_jmespath_expression,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *AuthMetadataExtractorConfiguration) Reset() {
	*x = AuthMetadataExtractorConfiguration{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMetadataExtractorConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMetadataExtractorConfiguration) ProtoMessage() {}

func (x *AuthMetadataExtractorConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMetadataExtractorConfiguration.ProtoReflect.Descriptor instead.
func (*AuthMetadataExtractorConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMetadataExtractorConfiguration) GetExternalIdExtractionJmespathExpression() *jmespath.Expression {
	if x != nil {
		return x.ExternalIdExtractionJmespathExpression
	}
	return nil
}

func (x *AuthMetadataExtractorConfiguration) GetDisplayNameExtractionJmespathExpression() *jmespath.Expression {
	if x != nil {
		return x.DisplayNameExtractionJmespathExpression
	}
	return nil
}

func (x *AuthMetadataExtractorConfiguration) GetUserInfoExtractionJmespathExpression() *jmespath.Expression {
	if x != nil {
		return x.UserInfoExtractionJmespathExpression
	}
	return nil
}

type BuildEventStreamService struct {
	state                        protoimpl.MessageState                                `protogen:"open.v1"`
	GrpcServers                  []*grpc.ServerConfiguration                           `protobuf:"bytes,1,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	Database                     *Database                                             `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	EnableBepFileUpload          bool                                                  `protobuf:"varint,4,opt,name=enable_bep_file_upload,json=enableBepFileUpload,proto3" json:"enable_bep_file_upload,omitempty"`
	EnableGraphqlPlayground      bool                                                  `protobuf:"varint,5,opt,name=enable_graphql_playground,json=enableGraphqlPlayground,proto3" json:"enable_graphql_playground,omitempty"`
	SaveDataLevel                *BuildEventStreamService_SaveDataLevel                `protobuf:"bytes,7,opt,name=save_data_level,json=saveDataLevel,proto3" json:"save_data_level,omitempty"`
	DatabaseCleanupConfiguration *BuildEventStreamService_DatabaseCleanupConfiguration `protobuf:"bytes,8,opt,name=database_cleanup_configuration,json=databaseCleanupConfiguration,proto3" json:"database_cleanup_configuration,omitempty"`
	AuthMetadataKeyConfiguration *AuthMetadataExtractorConfiguration                   `protobuf:"bytes,9,opt,name=auth_metadata_key_configuration,json=authMetadataKeyConfiguration,proto3" json:"auth_metadata_key_configuration,omitempty"`
	MinEventBatchDuration        *durationpb.Duration                                  `protobuf:"bytes,10,opt,name=min_event_batch_duration,json=minEventBatchDuration,proto3" json:"min_event_batch_duration,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *BuildEventStreamService) Reset() {
	*x = BuildEventStreamService{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEventStreamService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEventStreamService) ProtoMessage() {}

func (x *BuildEventStreamService) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEventStreamService.ProtoReflect.Descriptor instead.
func (*BuildEventStreamService) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{3}
}

func (x *BuildEventStreamService) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

func (x *BuildEventStreamService) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *BuildEventStreamService) GetEnableBepFileUpload() bool {
	if x != nil {
		return x.EnableBepFileUpload
	}
	return false
}

func (x *BuildEventStreamService) GetEnableGraphqlPlayground() bool {
	if x != nil {
		return x.EnableGraphqlPlayground
	}
	return false
}

func (x *BuildEventStreamService) GetSaveDataLevel() *BuildEventStreamService_SaveDataLevel {
	if x != nil {
		return x.SaveDataLevel
	}
	return nil
}

func (x *BuildEventStreamService) GetDatabaseCleanupConfiguration() *BuildEventStreamService_DatabaseCleanupConfiguration {
	if x != nil {
		return x.DatabaseCleanupConfiguration
	}
	return nil
}

func (x *BuildEventStreamService) GetAuthMetadataKeyConfiguration() *AuthMetadataExtractorConfiguration {
	if x != nil {
		return x.AuthMetadataKeyConfiguration
	}
	return nil
}

func (x *BuildEventStreamService) GetMinEventBatchDuration() *durationpb.Duration {
	if x != nil {
		return x.MinEventBatchDuration
	}
	return nil
}

type BrowserService struct {
	state                     protoimpl.MessageState             `protogen:"open.v1"`
	ContentAddressableStorage *blobstore.BlobAccessConfiguration `protobuf:"bytes,1,opt,name=content_addressable_storage,json=contentAddressableStorage,proto3" json:"content_addressable_storage,omitempty"`
	ActionCache               *blobstore.BlobAccessConfiguration `protobuf:"bytes,2,opt,name=action_cache,json=actionCache,proto3" json:"action_cache,omitempty"`
	InitialSizeClassCache     *blobstore.BlobAccessConfiguration `protobuf:"bytes,3,opt,name=initial_size_class_cache,json=initialSizeClassCache,proto3" json:"initial_size_class_cache,omitempty"`
	FileSystemAccessCache     *blobstore.BlobAccessConfiguration `protobuf:"bytes,4,opt,name=file_system_access_cache,json=fileSystemAccessCache,proto3" json:"file_system_access_cache,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *BrowserService) Reset() {
	*x = BrowserService{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserService) ProtoMessage() {}

func (x *BrowserService) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserService.ProtoReflect.Descriptor instead.
func (*BrowserService) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{4}
}

func (x *BrowserService) GetContentAddressableStorage() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.ContentAddressableStorage
	}
	return nil
}

func (x *BrowserService) GetActionCache() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.ActionCache
	}
	return nil
}

func (x *BrowserService) GetInitialSizeClassCache() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.InitialSizeClassCache
	}
	return nil
}

func (x *BrowserService) GetFileSystemAccessCache() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.FileSystemAccessCache
	}
	return nil
}

type SchedulerService struct {
	state                    protoimpl.MessageState        `protogen:"open.v1"`
	BuildQueueStateClient    *grpc.ClientConfiguration     `protobuf:"bytes,1,opt,name=build_queue_state_client,json=buildQueueStateClient,proto3" json:"build_queue_state_client,omitempty"`
	KillOperationsAuthorizer *auth.AuthorizerConfiguration `protobuf:"bytes,2,opt,name=kill_operations_authorizer,json=killOperationsAuthorizer,proto3" json:"kill_operations_authorizer,omitempty"`
	ListOperationsPageSize   uint32                        `protobuf:"varint,3,opt,name=listOperationsPageSize,proto3" json:"listOperationsPageSize,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SchedulerService) Reset() {
	*x = SchedulerService{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerService) ProtoMessage() {}

func (x *SchedulerService) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerService.ProtoReflect.Descriptor instead.
func (*SchedulerService) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{5}
}

func (x *SchedulerService) GetBuildQueueStateClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.BuildQueueStateClient
	}
	return nil
}

func (x *SchedulerService) GetKillOperationsAuthorizer() *auth.AuthorizerConfiguration {
	if x != nil {
		return x.KillOperationsAuthorizer
	}
	return nil
}

func (x *SchedulerService) GetListOperationsPageSize() uint32 {
	if x != nil {
		return x.ListOperationsPageSize
	}
	return 0
}

type ApplicationConfiguration struct {
	state                         protoimpl.MessageState        `protogen:"open.v1"`
	HttpServers                   []*server.Configuration       `protobuf:"bytes,1,rep,name=http_servers,json=httpServers,proto3" json:"http_servers,omitempty"`
	Global                        *global.Configuration         `protobuf:"bytes,2,opt,name=global,proto3" json:"global,omitempty"`
	BesServiceConfiguration       *BuildEventStreamService      `protobuf:"bytes,3,opt,name=bes_service_configuration,json=besServiceConfiguration,proto3" json:"bes_service_configuration,omitempty"`
	BrowserServiceConfiguration   *BrowserService               `protobuf:"bytes,4,opt,name=browser_service_configuration,json=browserServiceConfiguration,proto3" json:"browser_service_configuration,omitempty"`
	SchedulerServiceConfiguration *SchedulerService             `protobuf:"bytes,5,opt,name=scheduler_service_configuration,json=schedulerServiceConfiguration,proto3" json:"scheduler_service_configuration,omitempty"`
	MaximumMessageSizeBytes       int64                         `protobuf:"varint,6,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	InstanceNameAuthorizer        *auth.AuthorizerConfiguration `protobuf:"bytes,7,opt,name=instance_name_authorizer,json=instanceNameAuthorizer,proto3" json:"instance_name_authorizer,omitempty"`
	FrontendProxyUrl              string                        `protobuf:"bytes,8,opt,name=frontend_proxy_url,json=frontendProxyUrl,proto3" json:"frontend_proxy_url,omitempty"`
	AllowedOrigins                []string                      `protobuf:"bytes,9,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{6}
}

func (x *ApplicationConfiguration) GetHttpServers() []*server.Configuration {
	if x != nil {
		return x.HttpServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetBesServiceConfiguration() *BuildEventStreamService {
	if x != nil {
		return x.BesServiceConfiguration
	}
	return nil
}

func (x *ApplicationConfiguration) GetBrowserServiceConfiguration() *BrowserService {
	if x != nil {
		return x.BrowserServiceConfiguration
	}
	return nil
}

func (x *ApplicationConfiguration) GetSchedulerServiceConfiguration() *SchedulerService {
	if x != nil {
		return x.SchedulerServiceConfiguration
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetInstanceNameAuthorizer() *auth.AuthorizerConfiguration {
	if x != nil {
		return x.InstanceNameAuthorizer
	}
	return nil
}

func (x *ApplicationConfiguration) GetFrontendProxyUrl() string {
	if x != nil {
		return x.FrontendProxyUrl
	}
	return ""
}

func (x *ApplicationConfiguration) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

type Database_DatabaseConnectionPoolConfiguration struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxOpenConnections    int32                  `protobuf:"varint,1,opt,name=max_open_connections,json=maxOpenConnections,proto3" json:"max_open_connections,omitempty"`
	MaxIdleConnections    int32                  `protobuf:"varint,2,opt,name=max_idle_connections,json=maxIdleConnections,proto3" json:"max_idle_connections,omitempty"`
	ConnectionMaxLifetime *durationpb.Duration   `protobuf:"bytes,3,opt,name=connection_max_lifetime,json=connectionMaxLifetime,proto3" json:"connection_max_lifetime,omitempty"`
	ConnectionMaxIdleTime *durationpb.Duration   `protobuf:"bytes,4,opt,name=connection_max_idle_time,json=connectionMaxIdleTime,proto3" json:"connection_max_idle_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Database_DatabaseConnectionPoolConfiguration) Reset() {
	*x = Database_DatabaseConnectionPoolConfiguration{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database_DatabaseConnectionPoolConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_DatabaseConnectionPoolConfiguration) ProtoMessage() {}

func (x *Database_DatabaseConnectionPoolConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_DatabaseConnectionPoolConfiguration.ProtoReflect.Descriptor instead.
func (*Database_DatabaseConnectionPoolConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Database_DatabaseConnectionPoolConfiguration) GetMaxOpenConnections() int32 {
	if x != nil {
		return x.MaxOpenConnections
	}
	return 0
}

func (x *Database_DatabaseConnectionPoolConfiguration) GetMaxIdleConnections() int32 {
	if x != nil {
		return x.MaxIdleConnections
	}
	return 0
}

func (x *Database_DatabaseConnectionPoolConfiguration) GetConnectionMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnectionMaxLifetime
	}
	return nil
}

func (x *Database_DatabaseConnectionPoolConfiguration) GetConnectionMaxIdleTime() *durationpb.Duration {
	if x != nil {
		return x.ConnectionMaxIdleTime
	}
	return nil
}

type BuildEventStreamService_SaveDataLevel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Level:
	//
	//	*BuildEventStreamService_SaveDataLevel_Basic
	//	*BuildEventStreamService_SaveDataLevel_BasicAndTarget
	Level         isBuildEventStreamService_SaveDataLevel_Level `protobuf_oneof:"level"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEventStreamService_SaveDataLevel) Reset() {
	*x = BuildEventStreamService_SaveDataLevel{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEventStreamService_SaveDataLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEventStreamService_SaveDataLevel) ProtoMessage() {}

func (x *BuildEventStreamService_SaveDataLevel) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEventStreamService_SaveDataLevel.ProtoReflect.Descriptor instead.
func (*BuildEventStreamService_SaveDataLevel) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BuildEventStreamService_SaveDataLevel) GetLevel() isBuildEventStreamService_SaveDataLevel_Level {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *BuildEventStreamService_SaveDataLevel) GetBasic() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Level.(*BuildEventStreamService_SaveDataLevel_Basic); ok {
			return x.Basic
		}
	}
	return nil
}

func (x *BuildEventStreamService_SaveDataLevel) GetBasicAndTarget() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Level.(*BuildEventStreamService_SaveDataLevel_BasicAndTarget); ok {
			return x.BasicAndTarget
		}
	}
	return nil
}

type isBuildEventStreamService_SaveDataLevel_Level interface {
	isBuildEventStreamService_SaveDataLevel_Level()
}

type BuildEventStreamService_SaveDataLevel_Basic struct {
	Basic *emptypb.Empty `protobuf:"bytes,1,opt,name=basic,proto3,oneof"`
}

type BuildEventStreamService_SaveDataLevel_BasicAndTarget struct {
	BasicAndTarget *emptypb.Empty `protobuf:"bytes,2,opt,name=basic_and_target,json=basicAndTarget,proto3,oneof"`
}

func (*BuildEventStreamService_SaveDataLevel_Basic) isBuildEventStreamService_SaveDataLevel_Level() {}

func (*BuildEventStreamService_SaveDataLevel_BasicAndTarget) isBuildEventStreamService_SaveDataLevel_Level() {
}

type BuildEventStreamService_DatabaseCleanupConfiguration struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CleanupInterval          *durationpb.Duration   `protobuf:"bytes,1,opt,name=cleanup_interval,json=cleanupInterval,proto3" json:"cleanup_interval,omitempty"`
	InvocationMessageTimeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=invocation_message_timeout,json=invocationMessageTimeout,proto3" json:"invocation_message_timeout,omitempty"`
	InvocationRetention      *durationpb.Duration   `protobuf:"bytes,4,opt,name=invocation_retention,json=invocationRetention,proto3" json:"invocation_retention,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BuildEventStreamService_DatabaseCleanupConfiguration) Reset() {
	*x = BuildEventStreamService_DatabaseCleanupConfiguration{}
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEventStreamService_DatabaseCleanupConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEventStreamService_DatabaseCleanupConfiguration) ProtoMessage() {}

func (x *BuildEventStreamService_DatabaseCleanupConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEventStreamService_DatabaseCleanupConfiguration.ProtoReflect.Descriptor instead.
func (*BuildEventStreamService_DatabaseCleanupConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP(), []int{3, 1}
}

func (x *BuildEventStreamService_DatabaseCleanupConfiguration) GetCleanupInterval() *durationpb.Duration {
	if x != nil {
		return x.CleanupInterval
	}
	return nil
}

func (x *BuildEventStreamService_DatabaseCleanupConfiguration) GetInvocationMessageTimeout() *durationpb.Duration {
	if x != nil {
		return x.InvocationMessageTimeout
	}
	return nil
}

func (x *BuildEventStreamService_DatabaseCleanupConfiguration) GetInvocationRetention() *durationpb.Duration {
	if x != nil {
		return x.InvocationRetention
	}
	return nil
}

var File_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDesc = "" +
	"\n" +
	"Pgithub.com/buildbarn/bb-portal/pkg/proto/configuration/bb_portal/bb_portal.proto\x12!buildbarn.configuration.bb_portal\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/auth/auth.proto\x1aQgithub.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore/blobstore.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\x1aPgithub.com/buildbarn/bb-storage/pkg/proto/configuration/http/server/server.proto\x1aOgithub.com/buildbarn/bb-storage/pkg/proto/configuration/jmespath/jmespath.proto\"=\n" +
	"\x0ePostgresSource\x12+\n" +
	"\x11connection_string\x18\x01 \x01(\tR\x10connectionString\"\xb4\x04\n" +
	"\bDatabase\x12O\n" +
	"\bpostgres\x18\x02 \x01(\v21.buildbarn.configuration.bb_portal.PostgresSourceH\x00R\bpostgres\x12\x93\x01\n" +
	"\x1dconnection_pool_configuration\x18\x03 \x01(\v2O.buildbarn.configuration.bb_portal.Database.DatabaseConnectionPoolConfigurationR\x1bconnectionPoolConfiguration\x1a\xb0\x02\n" +
	"#DatabaseConnectionPoolConfiguration\x120\n" +
	"\x14max_open_connections\x18\x01 \x01(\x05R\x12maxOpenConnections\x120\n" +
	"\x14max_idle_connections\x18\x02 \x01(\x05R\x12maxIdleConnections\x12Q\n" +
	"\x17connection_max_lifetime\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x15connectionMaxLifetime\x12R\n" +
	"\x18connection_max_idle_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x15connectionMaxIdleTimeB\b\n" +
	"\x06sourceJ\x04\b\x01\x10\x02\"\xc3\x03\n" +
	"\"AuthMetadataExtractorConfiguration\x12\x88\x01\n" +
	"*external_id_extraction_jmespath_expression\x18\x01 \x01(\v2,.buildbarn.configuration.jmespath.ExpressionR&externalIdExtractionJmespathExpression\x12\x8a\x01\n" +
	"+display_name_extraction_jmespath_expression\x18\x02 \x01(\v2,.buildbarn.configuration.jmespath.ExpressionR'displayNameExtractionJmespathExpression\x12\x84\x01\n" +
	"(user_info_extraction_jmespath_expression\x18\x03 \x01(\v2,.buildbarn.configuration.jmespath.ExpressionR$userInfoExtractionJmespathExpression\"\xc7\t\n" +
	"\x17BuildEventStreamService\x12T\n" +
	"\fgrpc_servers\x18\x01 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServers\x12G\n" +
	"\bdatabase\x18\x02 \x01(\v2+.buildbarn.configuration.bb_portal.DatabaseR\bdatabase\x123\n" +
	"\x16enable_bep_file_upload\x18\x04 \x01(\bR\x13enableBepFileUpload\x12:\n" +
	"\x19enable_graphql_playground\x18\x05 \x01(\bR\x17enableGraphqlPlayground\x12p\n" +
	"\x0fsave_data_level\x18\a \x01(\v2H.buildbarn.configuration.bb_portal.BuildEventStreamService.SaveDataLevelR\rsaveDataLevel\x12\x9d\x01\n" +
	"\x1edatabase_cleanup_configuration\x18\b \x01(\v2W.buildbarn.configuration.bb_portal.BuildEventStreamService.DatabaseCleanupConfigurationR\x1cdatabaseCleanupConfiguration\x12\x8c\x01\n" +
	"\x1fauth_metadata_key_configuration\x18\t \x01(\v2E.buildbarn.configuration.bb_portal.AuthMetadataExtractorConfigurationR\x1cauthMetadataKeyConfiguration\x12R\n" +
	"\x18min_event_batch_duration\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x15minEventBatchDuration\x1a\x8c\x01\n" +
	"\rSaveDataLevel\x12.\n" +
	"\x05basic\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05basic\x12B\n" +
	"\x10basic_and_target\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x0ebasicAndTargetB\a\n" +
	"\x05level\x1a\x8b\x02\n" +
	"\x1cDatabaseCleanupConfiguration\x12D\n" +
	"\x10cleanup_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0fcleanupInterval\x12W\n" +
	"\x1ainvocation_message_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x18invocationMessageTimeout\x12L\n" +
	"\x14invocation_retention\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x13invocationRetentionJ\x04\b\x03\x10\x04J\x04\b\x06\x10\a\"\xd5\x03\n" +
	"\x0eBrowserService\x12z\n" +
	"\x1bcontent_addressable_storage\x18\x01 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x19contentAddressableStorage\x12]\n" +
	"\faction_cache\x18\x02 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\vactionCache\x12s\n" +
	"\x18initial_size_class_cache\x18\x03 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x15initialSizeClassCache\x12s\n" +
	"\x18file_system_access_cache\x18\x04 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x15fileSystemAccessCache\"\xab\x02\n" +
	"\x10SchedulerService\x12j\n" +
	"\x18build_queue_state_client\x18\x01 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x15buildQueueStateClient\x12s\n" +
	"\x1akill_operations_authorizer\x18\x02 \x01(\v25.buildbarn.configuration.auth.AuthorizerConfigurationR\x18killOperationsAuthorizer\x126\n" +
	"\x16listOperationsPageSize\x18\x03 \x01(\rR\x16listOperationsPageSize\"\xa9\x06\n" +
	"\x18ApplicationConfiguration\x12U\n" +
	"\fhttp_servers\x18\x01 \x03(\v22.buildbarn.configuration.http.server.ConfigurationR\vhttpServers\x12E\n" +
	"\x06global\x18\x02 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12v\n" +
	"\x19bes_service_configuration\x18\x03 \x01(\v2:.buildbarn.configuration.bb_portal.BuildEventStreamServiceR\x17besServiceConfiguration\x12u\n" +
	"\x1dbrowser_service_configuration\x18\x04 \x01(\v21.buildbarn.configuration.bb_portal.BrowserServiceR\x1bbrowserServiceConfiguration\x12{\n" +
	"\x1fscheduler_service_configuration\x18\x05 \x01(\v23.buildbarn.configuration.bb_portal.SchedulerServiceR\x1dschedulerServiceConfiguration\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\x06 \x01(\x03R\x17maximumMessageSizeBytes\x12o\n" +
	"\x18instance_name_authorizer\x18\a \x01(\v25.buildbarn.configuration.auth.AuthorizerConfigurationR\x16instanceNameAuthorizer\x12,\n" +
	"\x12frontend_proxy_url\x18\b \x01(\tR\x10frontendProxyUrl\x12'\n" +
	"\x0fallowed_origins\x18\t \x03(\tR\x0eallowedOriginsBBZ@github.com/buildbarn/bb-portal/pkg/proto/configuration/bb_portalb\x06proto3"

var (
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDesc), len(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDescData
}

var file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_goTypes = []any{
	(*PostgresSource)(nil),                                       // 0: buildbarn.configuration.bb_portal.PostgresSource
	(*Database)(nil),                                             // 1: buildbarn.configuration.bb_portal.Database
	(*AuthMetadataExtractorConfiguration)(nil),                   // 2: buildbarn.configuration.bb_portal.AuthMetadataExtractorConfiguration
	(*BuildEventStreamService)(nil),                              // 3: buildbarn.configuration.bb_portal.BuildEventStreamService
	(*BrowserService)(nil),                                       // 4: buildbarn.configuration.bb_portal.BrowserService
	(*SchedulerService)(nil),                                     // 5: buildbarn.configuration.bb_portal.SchedulerService
	(*ApplicationConfiguration)(nil),                             // 6: buildbarn.configuration.bb_portal.ApplicationConfiguration
	(*Database_DatabaseConnectionPoolConfiguration)(nil),         // 7: buildbarn.configuration.bb_portal.Database.DatabaseConnectionPoolConfiguration
	(*BuildEventStreamService_SaveDataLevel)(nil),                // 8: buildbarn.configuration.bb_portal.BuildEventStreamService.SaveDataLevel
	(*BuildEventStreamService_DatabaseCleanupConfiguration)(nil), // 9: buildbarn.configuration.bb_portal.BuildEventStreamService.DatabaseCleanupConfiguration
	(*jmespath.Expression)(nil),                                  // 10: buildbarn.configuration.jmespath.Expression
	(*grpc.ServerConfiguration)(nil),                             // 11: buildbarn.configuration.grpc.ServerConfiguration
	(*durationpb.Duration)(nil),                                  // 12: google.protobuf.Duration
	(*blobstore.BlobAccessConfiguration)(nil),                    // 13: buildbarn.configuration.blobstore.BlobAccessConfiguration
	(*grpc.ClientConfiguration)(nil),                             // 14: buildbarn.configuration.grpc.ClientConfiguration
	(*auth.AuthorizerConfiguration)(nil),                         // 15: buildbarn.configuration.auth.AuthorizerConfiguration
	(*server.Configuration)(nil),                                 // 16: buildbarn.configuration.http.server.Configuration
	(*global.Configuration)(nil),                                 // 17: buildbarn.configuration.global.Configuration
	(*emptypb.Empty)(nil),                                        // 18: google.protobuf.Empty
}
var file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_depIdxs = []int32{
	0,  // 0: buildbarn.configuration.bb_portal.Database.postgres:type_name -> buildbarn.configuration.bb_portal.PostgresSource
	7,  // 1: buildbarn.configuration.bb_portal.Database.connection_pool_configuration:type_name -> buildbarn.configuration.bb_portal.Database.DatabaseConnectionPoolConfiguration
	10, // 2: buildbarn.configuration.bb_portal.AuthMetadataExtractorConfiguration.external_id_extraction_jmespath_expression:type_name -> buildbarn.configuration.jmespath.Expression
	10, // 3: buildbarn.configuration.bb_portal.AuthMetadataExtractorConfiguration.display_name_extraction_jmespath_expression:type_name -> buildbarn.configuration.jmespath.Expression
	10, // 4: buildbarn.configuration.bb_portal.AuthMetadataExtractorConfiguration.user_info_extraction_jmespath_expression:type_name -> buildbarn.configuration.jmespath.Expression
	11, // 5: buildbarn.configuration.bb_portal.BuildEventStreamService.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	1,  // 6: buildbarn.configuration.bb_portal.BuildEventStreamService.database:type_name -> buildbarn.configuration.bb_portal.Database
	8,  // 7: buildbarn.configuration.bb_portal.BuildEventStreamService.save_data_level:type_name -> buildbarn.configuration.bb_portal.BuildEventStreamService.SaveDataLevel
	9,  // 8: buildbarn.configuration.bb_portal.BuildEventStreamService.database_cleanup_configuration:type_name -> buildbarn.configuration.bb_portal.BuildEventStreamService.DatabaseCleanupConfiguration
	2,  // 9: buildbarn.configuration.bb_portal.BuildEventStreamService.auth_metadata_key_configuration:type_name -> buildbarn.configuration.bb_portal.AuthMetadataExtractorConfiguration
	12, // 10: buildbarn.configuration.bb_portal.BuildEventStreamService.min_event_batch_duration:type_name -> google.protobuf.Duration
	13, // 11: buildbarn.configuration.bb_portal.BrowserService.content_addressable_storage:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	13, // 12: buildbarn.configuration.bb_portal.BrowserService.action_cache:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	13, // 13: buildbarn.configuration.bb_portal.BrowserService.initial_size_class_cache:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	13, // 14: buildbarn.configuration.bb_portal.BrowserService.file_system_access_cache:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	14, // 15: buildbarn.configuration.bb_portal.SchedulerService.build_queue_state_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	15, // 16: buildbarn.configuration.bb_portal.SchedulerService.kill_operations_authorizer:type_name -> buildbarn.configuration.auth.AuthorizerConfiguration
	16, // 17: buildbarn.configuration.bb_portal.ApplicationConfiguration.http_servers:type_name -> buildbarn.configuration.http.server.Configuration
	17, // 18: buildbarn.configuration.bb_portal.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	3,  // 19: buildbarn.configuration.bb_portal.ApplicationConfiguration.bes_service_configuration:type_name -> buildbarn.configuration.bb_portal.BuildEventStreamService
	4,  // 20: buildbarn.configuration.bb_portal.ApplicationConfiguration.browser_service_configuration:type_name -> buildbarn.configuration.bb_portal.BrowserService
	5,  // 21: buildbarn.configuration.bb_portal.ApplicationConfiguration.scheduler_service_configuration:type_name -> buildbarn.configuration.bb_portal.SchedulerService
	15, // 22: buildbarn.configuration.bb_portal.ApplicationConfiguration.instance_name_authorizer:type_name -> buildbarn.configuration.auth.AuthorizerConfiguration
	12, // 23: buildbarn.configuration.bb_portal.Database.DatabaseConnectionPoolConfiguration.connection_max_lifetime:type_name -> google.protobuf.Duration
	12, // 24: buildbarn.configuration.bb_portal.Database.DatabaseConnectionPoolConfiguration.connection_max_idle_time:type_name -> google.protobuf.Duration
	18, // 25: buildbarn.configuration.bb_portal.BuildEventStreamService.SaveDataLevel.basic:type_name -> google.protobuf.Empty
	18, // 26: buildbarn.configuration.bb_portal.BuildEventStreamService.SaveDataLevel.basic_and_target:type_name -> google.protobuf.Empty
	12, // 27: buildbarn.configuration.bb_portal.BuildEventStreamService.DatabaseCleanupConfiguration.cleanup_interval:type_name -> google.protobuf.Duration
	12, // 28: buildbarn.configuration.bb_portal.BuildEventStreamService.DatabaseCleanupConfiguration.invocation_message_timeout:type_name -> google.protobuf.Duration
	12, // 29: buildbarn.configuration.bb_portal.BuildEventStreamService.DatabaseCleanupConfiguration.invocation_retention:type_name -> google.protobuf.Duration
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_init()
}
func file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_init() {
	if File_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[1].OneofWrappers = []any{
		(*Database_Postgres)(nil),
	}
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes[8].OneofWrappers = []any{
		(*BuildEventStreamService_SaveDataLevel_Basic)(nil),
		(*BuildEventStreamService_SaveDataLevel_BasicAndTarget)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDesc), len(file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto = out.File
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_goTypes = nil
	file_github_com_buildbarn_bb_portal_pkg_proto_configuration_bb_portal_bb_portal_proto_depIdxs = nil
}
