load("@rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "postgres",
    srcs = ["main.go"],
    data = ["//internal/database/embedded:extraced_embedded_postgres"],
    importpath = "github.com/buildbarn/bb-portal/test/itest/postgres",
    visibility = ["//test/itest:__pkg__"],
    deps = ["@rules_go//go/runfiles"],
)
