/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as BazelInvocationsRouteImport } from './routes/bazel-invocations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as TargetsIndexRouteImport } from './routes/targets.index'
import { Route as SchedulerIndexRouteImport } from './routes/scheduler.index'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as BuildsIndexRouteImport } from './routes/builds.index'
import { Route as BrowserIndexRouteImport } from './routes/browser.index'
import { Route as BazelInvocationsIndexRouteImport } from './routes/bazel-invocations.index'
import { Route as UsersUserUUIDRouteImport } from './routes/users.$userUUID'
import { Route as SchedulerWorkerRouteImport } from './routes/scheduler.worker'
import { Route as OperationsOperationIDRouteImport } from './routes/operations.$operationID'
import { Route as BuildsBuildUUIDRouteImport } from './routes/builds.$buildUUID'
import { Route as BrowserSplatRouteImport } from './routes/browser.$'
import { Route as BazelInvocationsInvocationIDRouteImport } from './routes/bazel-invocations.$invocationID'
import { Route as TargetsTargetIDIndexRouteImport } from './routes/targets.$targetID.index'
import { Route as BazelInvocationsInvocationIDIndexRouteImport } from './routes/bazel-invocations.$invocationID/index'
import { Route as TargetsTargetIDTestsRouteImport } from './routes/targets.$targetID.tests'
import { Route as BazelInvocationsInvocationIDTestsRouteImport } from './routes/bazel-invocations.$invocationID/tests'
import { Route as BazelInvocationsInvocationIDTargetsRouteImport } from './routes/bazel-invocations.$invocationID/targets'
import { Route as BazelInvocationsInvocationIDTagsRouteImport } from './routes/bazel-invocations.$invocationID/tags'
import { Route as BazelInvocationsInvocationIDSystemMetricsRouteImport } from './routes/bazel-invocations.$invocationID/system-metrics'
import { Route as BazelInvocationsInvocationIDSourceControlRouteImport } from './routes/bazel-invocations.$invocationID/source-control'
import { Route as BazelInvocationsInvocationIDMemoryRouteImport } from './routes/bazel-invocations.$invocationID/memory'
import { Route as BazelInvocationsInvocationIDLogRouteImport } from './routes/bazel-invocations.$invocationID/log'
import { Route as BazelInvocationsInvocationIDCommandLineRouteImport } from './routes/bazel-invocations.$invocationID/command-line'
import { Route as BazelInvocationsInvocationIDArtifactsRouteImport } from './routes/bazel-invocations.$invocationID/artifacts'
import { Route as BazelInvocationsInvocationIDActionsRouteImport } from './routes/bazel-invocations.$invocationID/actions'
import { Route as BazelInvocationsInvocationIDActionStatisticsRouteImport } from './routes/bazel-invocations.$invocationID/action-statistics'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const BazelInvocationsRoute = BazelInvocationsRouteImport.update({
  id: '/bazel-invocations',
  path: '/bazel-invocations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const TargetsIndexRoute = TargetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TargetsRoute,
} as any)
const SchedulerIndexRoute = SchedulerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchedulerRoute,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildsRoute,
} as any)
const BrowserIndexRoute = BrowserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowserRoute,
} as any)
const BazelInvocationsIndexRoute = BazelInvocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BazelInvocationsRoute,
} as any)
const UsersUserUUIDRoute = UsersUserUUIDRouteImport.update({
  id: '/users/$userUUID',
  path: '/users/$userUUID',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerWorkerRoute = SchedulerWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => SchedulerRoute,
} as any)
const OperationsOperationIDRoute = OperationsOperationIDRouteImport.update({
  id: '/$operationID',
  path: '/$operationID',
  getParentRoute: () => OperationsRoute,
} as any)
const BuildsBuildUUIDRoute = BuildsBuildUUIDRouteImport.update({
  id: '/$buildUUID',
  path: '/$buildUUID',
  getParentRoute: () => BuildsRoute,
} as any)
const BrowserSplatRoute = BrowserSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BrowserRoute,
} as any)
const BazelInvocationsInvocationIDRoute =
  BazelInvocationsInvocationIDRouteImport.update({
    id: '/$invocationID',
    path: '/$invocationID',
    getParentRoute: () => BazelInvocationsRoute,
  } as any)
const TargetsTargetIDIndexRoute = TargetsTargetIDIndexRouteImport.update({
  id: '/$targetID/',
  path: '/$targetID/',
  getParentRoute: () => TargetsRoute,
} as any)
const BazelInvocationsInvocationIDIndexRoute =
  BazelInvocationsInvocationIDIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const TargetsTargetIDTestsRoute = TargetsTargetIDTestsRouteImport.update({
  id: '/$targetID/tests',
  path: '/$targetID/tests',
  getParentRoute: () => TargetsRoute,
} as any)
const BazelInvocationsInvocationIDTestsRoute =
  BazelInvocationsInvocationIDTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDTargetsRoute =
  BazelInvocationsInvocationIDTargetsRouteImport.update({
    id: '/targets',
    path: '/targets',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDTagsRoute =
  BazelInvocationsInvocationIDTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDSystemMetricsRoute =
  BazelInvocationsInvocationIDSystemMetricsRouteImport.update({
    id: '/system-metrics',
    path: '/system-metrics',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDSourceControlRoute =
  BazelInvocationsInvocationIDSourceControlRouteImport.update({
    id: '/source-control',
    path: '/source-control',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDMemoryRoute =
  BazelInvocationsInvocationIDMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDLogRoute =
  BazelInvocationsInvocationIDLogRouteImport.update({
    id: '/log',
    path: '/log',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDCommandLineRoute =
  BazelInvocationsInvocationIDCommandLineRouteImport.update({
    id: '/command-line',
    path: '/command-line',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDArtifactsRoute =
  BazelInvocationsInvocationIDArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDActionsRoute =
  BazelInvocationsInvocationIDActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)
const BazelInvocationsInvocationIDActionStatisticsRoute =
  BazelInvocationsInvocationIDActionStatisticsRouteImport.update({
    id: '/action-statistics',
    path: '/action-statistics',
    getParentRoute: () => BazelInvocationsInvocationIDRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bazel-invocations': typeof BazelInvocationsRouteWithChildren
  '/browser': typeof BrowserRouteWithChildren
  '/builds': typeof BuildsRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/scheduler': typeof SchedulerRouteWithChildren
  '/targets': typeof TargetsRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/trends': typeof TrendsRoute
  '/bazel-invocations/$invocationID': typeof BazelInvocationsInvocationIDRouteWithChildren
  '/browser/$': typeof BrowserSplatRoute
  '/builds/$buildUUID': typeof BuildsBuildUUIDRoute
  '/operations/$operationID': typeof OperationsOperationIDRoute
  '/scheduler/worker': typeof SchedulerWorkerRoute
  '/users/$userUUID': typeof UsersUserUUIDRoute
  '/bazel-invocations/': typeof BazelInvocationsIndexRoute
  '/browser/': typeof BrowserIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/scheduler/': typeof SchedulerIndexRoute
  '/targets/': typeof TargetsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/bazel-invocations/$invocationID/action-statistics': typeof BazelInvocationsInvocationIDActionStatisticsRoute
  '/bazel-invocations/$invocationID/actions': typeof BazelInvocationsInvocationIDActionsRoute
  '/bazel-invocations/$invocationID/artifacts': typeof BazelInvocationsInvocationIDArtifactsRoute
  '/bazel-invocations/$invocationID/command-line': typeof BazelInvocationsInvocationIDCommandLineRoute
  '/bazel-invocations/$invocationID/log': typeof BazelInvocationsInvocationIDLogRoute
  '/bazel-invocations/$invocationID/memory': typeof BazelInvocationsInvocationIDMemoryRoute
  '/bazel-invocations/$invocationID/source-control': typeof BazelInvocationsInvocationIDSourceControlRoute
  '/bazel-invocations/$invocationID/system-metrics': typeof BazelInvocationsInvocationIDSystemMetricsRoute
  '/bazel-invocations/$invocationID/tags': typeof BazelInvocationsInvocationIDTagsRoute
  '/bazel-invocations/$invocationID/targets': typeof BazelInvocationsInvocationIDTargetsRoute
  '/bazel-invocations/$invocationID/tests': typeof BazelInvocationsInvocationIDTestsRoute
  '/targets/$targetID/tests': typeof TargetsTargetIDTestsRoute
  '/bazel-invocations/$invocationID/': typeof BazelInvocationsInvocationIDIndexRoute
  '/targets/$targetID/': typeof TargetsTargetIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trends': typeof TrendsRoute
  '/browser/$': typeof BrowserSplatRoute
  '/builds/$buildUUID': typeof BuildsBuildUUIDRoute
  '/operations/$operationID': typeof OperationsOperationIDRoute
  '/scheduler/worker': typeof SchedulerWorkerRoute
  '/users/$userUUID': typeof UsersUserUUIDRoute
  '/bazel-invocations': typeof BazelInvocationsIndexRoute
  '/browser': typeof BrowserIndexRoute
  '/builds': typeof BuildsIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/scheduler': typeof SchedulerIndexRoute
  '/targets': typeof TargetsIndexRoute
  '/tests': typeof TestsIndexRoute
  '/bazel-invocations/$invocationID/action-statistics': typeof BazelInvocationsInvocationIDActionStatisticsRoute
  '/bazel-invocations/$invocationID/actions': typeof BazelInvocationsInvocationIDActionsRoute
  '/bazel-invocations/$invocationID/artifacts': typeof BazelInvocationsInvocationIDArtifactsRoute
  '/bazel-invocations/$invocationID/command-line': typeof BazelInvocationsInvocationIDCommandLineRoute
  '/bazel-invocations/$invocationID/log': typeof BazelInvocationsInvocationIDLogRoute
  '/bazel-invocations/$invocationID/memory': typeof BazelInvocationsInvocationIDMemoryRoute
  '/bazel-invocations/$invocationID/source-control': typeof BazelInvocationsInvocationIDSourceControlRoute
  '/bazel-invocations/$invocationID/system-metrics': typeof BazelInvocationsInvocationIDSystemMetricsRoute
  '/bazel-invocations/$invocationID/tags': typeof BazelInvocationsInvocationIDTagsRoute
  '/bazel-invocations/$invocationID/targets': typeof BazelInvocationsInvocationIDTargetsRoute
  '/bazel-invocations/$invocationID/tests': typeof BazelInvocationsInvocationIDTestsRoute
  '/targets/$targetID/tests': typeof TargetsTargetIDTestsRoute
  '/bazel-invocations/$invocationID': typeof BazelInvocationsInvocationIDIndexRoute
  '/targets/$targetID': typeof TargetsTargetIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bazel-invocations': typeof BazelInvocationsRouteWithChildren
  '/browser': typeof BrowserRouteWithChildren
  '/builds': typeof BuildsRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/scheduler': typeof SchedulerRouteWithChildren
  '/targets': typeof TargetsRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/trends': typeof TrendsRoute
  '/bazel-invocations/$invocationID': typeof BazelInvocationsInvocationIDRouteWithChildren
  '/browser/$': typeof BrowserSplatRoute
  '/builds/$buildUUID': typeof BuildsBuildUUIDRoute
  '/operations/$operationID': typeof OperationsOperationIDRoute
  '/scheduler/worker': typeof SchedulerWorkerRoute
  '/users/$userUUID': typeof UsersUserUUIDRoute
  '/bazel-invocations/': typeof BazelInvocationsIndexRoute
  '/browser/': typeof BrowserIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/scheduler/': typeof SchedulerIndexRoute
  '/targets/': typeof TargetsIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/bazel-invocations/$invocationID/action-statistics': typeof BazelInvocationsInvocationIDActionStatisticsRoute
  '/bazel-invocations/$invocationID/actions': typeof BazelInvocationsInvocationIDActionsRoute
  '/bazel-invocations/$invocationID/artifacts': typeof BazelInvocationsInvocationIDArtifactsRoute
  '/bazel-invocations/$invocationID/command-line': typeof BazelInvocationsInvocationIDCommandLineRoute
  '/bazel-invocations/$invocationID/log': typeof BazelInvocationsInvocationIDLogRoute
  '/bazel-invocations/$invocationID/memory': typeof BazelInvocationsInvocationIDMemoryRoute
  '/bazel-invocations/$invocationID/source-control': typeof BazelInvocationsInvocationIDSourceControlRoute
  '/bazel-invocations/$invocationID/system-metrics': typeof BazelInvocationsInvocationIDSystemMetricsRoute
  '/bazel-invocations/$invocationID/tags': typeof BazelInvocationsInvocationIDTagsRoute
  '/bazel-invocations/$invocationID/targets': typeof BazelInvocationsInvocationIDTargetsRoute
  '/bazel-invocations/$invocationID/tests': typeof BazelInvocationsInvocationIDTestsRoute
  '/targets/$targetID/tests': typeof TargetsTargetIDTestsRoute
  '/bazel-invocations/$invocationID/': typeof BazelInvocationsInvocationIDIndexRoute
  '/targets/$targetID/': typeof TargetsTargetIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bazel-invocations'
    | '/browser'
    | '/builds'
    | '/operations'
    | '/scheduler'
    | '/targets'
    | '/tests'
    | '/trends'
    | '/bazel-invocations/$invocationID'
    | '/browser/$'
    | '/builds/$buildUUID'
    | '/operations/$operationID'
    | '/scheduler/worker'
    | '/users/$userUUID'
    | '/bazel-invocations/'
    | '/browser/'
    | '/builds/'
    | '/operations/'
    | '/scheduler/'
    | '/targets/'
    | '/tests/'
    | '/bazel-invocations/$invocationID/action-statistics'
    | '/bazel-invocations/$invocationID/actions'
    | '/bazel-invocations/$invocationID/artifacts'
    | '/bazel-invocations/$invocationID/command-line'
    | '/bazel-invocations/$invocationID/log'
    | '/bazel-invocations/$invocationID/memory'
    | '/bazel-invocations/$invocationID/source-control'
    | '/bazel-invocations/$invocationID/system-metrics'
    | '/bazel-invocations/$invocationID/tags'
    | '/bazel-invocations/$invocationID/targets'
    | '/bazel-invocations/$invocationID/tests'
    | '/targets/$targetID/tests'
    | '/bazel-invocations/$invocationID/'
    | '/targets/$targetID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trends'
    | '/browser/$'
    | '/builds/$buildUUID'
    | '/operations/$operationID'
    | '/scheduler/worker'
    | '/users/$userUUID'
    | '/bazel-invocations'
    | '/browser'
    | '/builds'
    | '/operations'
    | '/scheduler'
    | '/targets'
    | '/tests'
    | '/bazel-invocations/$invocationID/action-statistics'
    | '/bazel-invocations/$invocationID/actions'
    | '/bazel-invocations/$invocationID/artifacts'
    | '/bazel-invocations/$invocationID/command-line'
    | '/bazel-invocations/$invocationID/log'
    | '/bazel-invocations/$invocationID/memory'
    | '/bazel-invocations/$invocationID/source-control'
    | '/bazel-invocations/$invocationID/system-metrics'
    | '/bazel-invocations/$invocationID/tags'
    | '/bazel-invocations/$invocationID/targets'
    | '/bazel-invocations/$invocationID/tests'
    | '/targets/$targetID/tests'
    | '/bazel-invocations/$invocationID'
    | '/targets/$targetID'
  id:
    | '__root__'
    | '/'
    | '/bazel-invocations'
    | '/browser'
    | '/builds'
    | '/operations'
    | '/scheduler'
    | '/targets'
    | '/tests'
    | '/trends'
    | '/bazel-invocations/$invocationID'
    | '/browser/$'
    | '/builds/$buildUUID'
    | '/operations/$operationID'
    | '/scheduler/worker'
    | '/users/$userUUID'
    | '/bazel-invocations/'
    | '/browser/'
    | '/builds/'
    | '/operations/'
    | '/scheduler/'
    | '/targets/'
    | '/tests/'
    | '/bazel-invocations/$invocationID/action-statistics'
    | '/bazel-invocations/$invocationID/actions'
    | '/bazel-invocations/$invocationID/artifacts'
    | '/bazel-invocations/$invocationID/command-line'
    | '/bazel-invocations/$invocationID/log'
    | '/bazel-invocations/$invocationID/memory'
    | '/bazel-invocations/$invocationID/source-control'
    | '/bazel-invocations/$invocationID/system-metrics'
    | '/bazel-invocations/$invocationID/tags'
    | '/bazel-invocations/$invocationID/targets'
    | '/bazel-invocations/$invocationID/tests'
    | '/targets/$targetID/tests'
    | '/bazel-invocations/$invocationID/'
    | '/targets/$targetID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BazelInvocationsRoute: typeof BazelInvocationsRouteWithChildren
  BrowserRoute: typeof BrowserRouteWithChildren
  BuildsRoute: typeof BuildsRouteWithChildren
  OperationsRoute: typeof OperationsRouteWithChildren
  SchedulerRoute: typeof SchedulerRouteWithChildren
  TargetsRoute: typeof TargetsRouteWithChildren
  TestsRoute: typeof TestsRouteWithChildren
  TrendsRoute: typeof TrendsRoute
  UsersUserUUIDRoute: typeof UsersUserUUIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazel-invocations': {
      id: '/bazel-invocations'
      path: '/bazel-invocations'
      fullPath: '/bazel-invocations'
      preLoaderRoute: typeof BazelInvocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/targets/': {
      id: '/targets/'
      path: '/'
      fullPath: '/targets/'
      preLoaderRoute: typeof TargetsIndexRouteImport
      parentRoute: typeof TargetsRoute
    }
    '/scheduler/': {
      id: '/scheduler/'
      path: '/'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof SchedulerIndexRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/builds/': {
      id: '/builds/'
      path: '/'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof BuildsRoute
    }
    '/browser/': {
      id: '/browser/'
      path: '/'
      fullPath: '/browser/'
      preLoaderRoute: typeof BrowserIndexRouteImport
      parentRoute: typeof BrowserRoute
    }
    '/bazel-invocations/': {
      id: '/bazel-invocations/'
      path: '/'
      fullPath: '/bazel-invocations/'
      preLoaderRoute: typeof BazelInvocationsIndexRouteImport
      parentRoute: typeof BazelInvocationsRoute
    }
    '/users/$userUUID': {
      id: '/users/$userUUID'
      path: '/users/$userUUID'
      fullPath: '/users/$userUUID'
      preLoaderRoute: typeof UsersUserUUIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler/worker': {
      id: '/scheduler/worker'
      path: '/worker'
      fullPath: '/scheduler/worker'
      preLoaderRoute: typeof SchedulerWorkerRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/operations/$operationID': {
      id: '/operations/$operationID'
      path: '/$operationID'
      fullPath: '/operations/$operationID'
      preLoaderRoute: typeof OperationsOperationIDRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/builds/$buildUUID': {
      id: '/builds/$buildUUID'
      path: '/$buildUUID'
      fullPath: '/builds/$buildUUID'
      preLoaderRoute: typeof BuildsBuildUUIDRouteImport
      parentRoute: typeof BuildsRoute
    }
    '/browser/$': {
      id: '/browser/$'
      path: '/$'
      fullPath: '/browser/$'
      preLoaderRoute: typeof BrowserSplatRouteImport
      parentRoute: typeof BrowserRoute
    }
    '/bazel-invocations/$invocationID': {
      id: '/bazel-invocations/$invocationID'
      path: '/$invocationID'
      fullPath: '/bazel-invocations/$invocationID'
      preLoaderRoute: typeof BazelInvocationsInvocationIDRouteImport
      parentRoute: typeof BazelInvocationsRoute
    }
    '/targets/$targetID/': {
      id: '/targets/$targetID/'
      path: '/$targetID'
      fullPath: '/targets/$targetID/'
      preLoaderRoute: typeof TargetsTargetIDIndexRouteImport
      parentRoute: typeof TargetsRoute
    }
    '/bazel-invocations/$invocationID/': {
      id: '/bazel-invocations/$invocationID/'
      path: '/'
      fullPath: '/bazel-invocations/$invocationID/'
      preLoaderRoute: typeof BazelInvocationsInvocationIDIndexRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/targets/$targetID/tests': {
      id: '/targets/$targetID/tests'
      path: '/$targetID/tests'
      fullPath: '/targets/$targetID/tests'
      preLoaderRoute: typeof TargetsTargetIDTestsRouteImport
      parentRoute: typeof TargetsRoute
    }
    '/bazel-invocations/$invocationID/tests': {
      id: '/bazel-invocations/$invocationID/tests'
      path: '/tests'
      fullPath: '/bazel-invocations/$invocationID/tests'
      preLoaderRoute: typeof BazelInvocationsInvocationIDTestsRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/targets': {
      id: '/bazel-invocations/$invocationID/targets'
      path: '/targets'
      fullPath: '/bazel-invocations/$invocationID/targets'
      preLoaderRoute: typeof BazelInvocationsInvocationIDTargetsRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/tags': {
      id: '/bazel-invocations/$invocationID/tags'
      path: '/tags'
      fullPath: '/bazel-invocations/$invocationID/tags'
      preLoaderRoute: typeof BazelInvocationsInvocationIDTagsRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/system-metrics': {
      id: '/bazel-invocations/$invocationID/system-metrics'
      path: '/system-metrics'
      fullPath: '/bazel-invocations/$invocationID/system-metrics'
      preLoaderRoute: typeof BazelInvocationsInvocationIDSystemMetricsRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/source-control': {
      id: '/bazel-invocations/$invocationID/source-control'
      path: '/source-control'
      fullPath: '/bazel-invocations/$invocationID/source-control'
      preLoaderRoute: typeof BazelInvocationsInvocationIDSourceControlRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/memory': {
      id: '/bazel-invocations/$invocationID/memory'
      path: '/memory'
      fullPath: '/bazel-invocations/$invocationID/memory'
      preLoaderRoute: typeof BazelInvocationsInvocationIDMemoryRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/log': {
      id: '/bazel-invocations/$invocationID/log'
      path: '/log'
      fullPath: '/bazel-invocations/$invocationID/log'
      preLoaderRoute: typeof BazelInvocationsInvocationIDLogRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/command-line': {
      id: '/bazel-invocations/$invocationID/command-line'
      path: '/command-line'
      fullPath: '/bazel-invocations/$invocationID/command-line'
      preLoaderRoute: typeof BazelInvocationsInvocationIDCommandLineRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/artifacts': {
      id: '/bazel-invocations/$invocationID/artifacts'
      path: '/artifacts'
      fullPath: '/bazel-invocations/$invocationID/artifacts'
      preLoaderRoute: typeof BazelInvocationsInvocationIDArtifactsRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/actions': {
      id: '/bazel-invocations/$invocationID/actions'
      path: '/actions'
      fullPath: '/bazel-invocations/$invocationID/actions'
      preLoaderRoute: typeof BazelInvocationsInvocationIDActionsRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
    '/bazel-invocations/$invocationID/action-statistics': {
      id: '/bazel-invocations/$invocationID/action-statistics'
      path: '/action-statistics'
      fullPath: '/bazel-invocations/$invocationID/action-statistics'
      preLoaderRoute: typeof BazelInvocationsInvocationIDActionStatisticsRouteImport
      parentRoute: typeof BazelInvocationsInvocationIDRoute
    }
  }
}

interface BazelInvocationsInvocationIDRouteChildren {
  BazelInvocationsInvocationIDActionStatisticsRoute: typeof BazelInvocationsInvocationIDActionStatisticsRoute
  BazelInvocationsInvocationIDActionsRoute: typeof BazelInvocationsInvocationIDActionsRoute
  BazelInvocationsInvocationIDArtifactsRoute: typeof BazelInvocationsInvocationIDArtifactsRoute
  BazelInvocationsInvocationIDCommandLineRoute: typeof BazelInvocationsInvocationIDCommandLineRoute
  BazelInvocationsInvocationIDLogRoute: typeof BazelInvocationsInvocationIDLogRoute
  BazelInvocationsInvocationIDMemoryRoute: typeof BazelInvocationsInvocationIDMemoryRoute
  BazelInvocationsInvocationIDSourceControlRoute: typeof BazelInvocationsInvocationIDSourceControlRoute
  BazelInvocationsInvocationIDSystemMetricsRoute: typeof BazelInvocationsInvocationIDSystemMetricsRoute
  BazelInvocationsInvocationIDTagsRoute: typeof BazelInvocationsInvocationIDTagsRoute
  BazelInvocationsInvocationIDTargetsRoute: typeof BazelInvocationsInvocationIDTargetsRoute
  BazelInvocationsInvocationIDTestsRoute: typeof BazelInvocationsInvocationIDTestsRoute
  BazelInvocationsInvocationIDIndexRoute: typeof BazelInvocationsInvocationIDIndexRoute
}

const BazelInvocationsInvocationIDRouteChildren: BazelInvocationsInvocationIDRouteChildren =
  {
    BazelInvocationsInvocationIDActionStatisticsRoute:
      BazelInvocationsInvocationIDActionStatisticsRoute,
    BazelInvocationsInvocationIDActionsRoute:
      BazelInvocationsInvocationIDActionsRoute,
    BazelInvocationsInvocationIDArtifactsRoute:
      BazelInvocationsInvocationIDArtifactsRoute,
    BazelInvocationsInvocationIDCommandLineRoute:
      BazelInvocationsInvocationIDCommandLineRoute,
    BazelInvocationsInvocationIDLogRoute: BazelInvocationsInvocationIDLogRoute,
    BazelInvocationsInvocationIDMemoryRoute:
      BazelInvocationsInvocationIDMemoryRoute,
    BazelInvocationsInvocationIDSourceControlRoute:
      BazelInvocationsInvocationIDSourceControlRoute,
    BazelInvocationsInvocationIDSystemMetricsRoute:
      BazelInvocationsInvocationIDSystemMetricsRoute,
    BazelInvocationsInvocationIDTagsRoute:
      BazelInvocationsInvocationIDTagsRoute,
    BazelInvocationsInvocationIDTargetsRoute:
      BazelInvocationsInvocationIDTargetsRoute,
    BazelInvocationsInvocationIDTestsRoute:
      BazelInvocationsInvocationIDTestsRoute,
    BazelInvocationsInvocationIDIndexRoute:
      BazelInvocationsInvocationIDIndexRoute,
  }

const BazelInvocationsInvocationIDRouteWithChildren =
  BazelInvocationsInvocationIDRoute._addFileChildren(
    BazelInvocationsInvocationIDRouteChildren,
  )

interface BazelInvocationsRouteChildren {
  BazelInvocationsInvocationIDRoute: typeof BazelInvocationsInvocationIDRouteWithChildren
  BazelInvocationsIndexRoute: typeof BazelInvocationsIndexRoute
}

const BazelInvocationsRouteChildren: BazelInvocationsRouteChildren = {
  BazelInvocationsInvocationIDRoute:
    BazelInvocationsInvocationIDRouteWithChildren,
  BazelInvocationsIndexRoute: BazelInvocationsIndexRoute,
}

const BazelInvocationsRouteWithChildren =
  BazelInvocationsRoute._addFileChildren(BazelInvocationsRouteChildren)

interface BrowserRouteChildren {
  BrowserSplatRoute: typeof BrowserSplatRoute
  BrowserIndexRoute: typeof BrowserIndexRoute
}

const BrowserRouteChildren: BrowserRouteChildren = {
  BrowserSplatRoute: BrowserSplatRoute,
  BrowserIndexRoute: BrowserIndexRoute,
}

const BrowserRouteWithChildren =
  BrowserRoute._addFileChildren(BrowserRouteChildren)

interface BuildsRouteChildren {
  BuildsBuildUUIDRoute: typeof BuildsBuildUUIDRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
}

const BuildsRouteChildren: BuildsRouteChildren = {
  BuildsBuildUUIDRoute: BuildsBuildUUIDRoute,
  BuildsIndexRoute: BuildsIndexRoute,
}

const BuildsRouteWithChildren =
  BuildsRoute._addFileChildren(BuildsRouteChildren)

interface OperationsRouteChildren {
  OperationsOperationIDRoute: typeof OperationsOperationIDRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsOperationIDRoute: OperationsOperationIDRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface SchedulerRouteChildren {
  SchedulerWorkerRoute: typeof SchedulerWorkerRoute
  SchedulerIndexRoute: typeof SchedulerIndexRoute
}

const SchedulerRouteChildren: SchedulerRouteChildren = {
  SchedulerWorkerRoute: SchedulerWorkerRoute,
  SchedulerIndexRoute: SchedulerIndexRoute,
}

const SchedulerRouteWithChildren = SchedulerRoute._addFileChildren(
  SchedulerRouteChildren,
)

interface TargetsRouteChildren {
  TargetsIndexRoute: typeof TargetsIndexRoute
  TargetsTargetIDTestsRoute: typeof TargetsTargetIDTestsRoute
  TargetsTargetIDIndexRoute: typeof TargetsTargetIDIndexRoute
}

const TargetsRouteChildren: TargetsRouteChildren = {
  TargetsIndexRoute: TargetsIndexRoute,
  TargetsTargetIDTestsRoute: TargetsTargetIDTestsRoute,
  TargetsTargetIDIndexRoute: TargetsTargetIDIndexRoute,
}

const TargetsRouteWithChildren =
  TargetsRoute._addFileChildren(TargetsRouteChildren)

interface TestsRouteChildren {
  TestsIndexRoute: typeof TestsIndexRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsIndexRoute: TestsIndexRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BazelInvocationsRoute: BazelInvocationsRouteWithChildren,
  BrowserRoute: BrowserRouteWithChildren,
  BuildsRoute: BuildsRouteWithChildren,
  OperationsRoute: OperationsRouteWithChildren,
  SchedulerRoute: SchedulerRouteWithChildren,
  TargetsRoute: TargetsRouteWithChildren,
  TestsRoute: TestsRouteWithChildren,
  TrendsRoute: TrendsRoute,
  UsersUserUUIDRoute: UsersUserUUIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
