/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query FindBazelInvocations(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BazelInvocationNode\n        }\n      }\n    }\n  }\n": typeof types.FindBazelInvocationsDocument,
    "\n  fragment BazelInvocationNode on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    username\n    authenticatedUser {\n      userUUID\n      displayName\n    }\n    endedAt\n    exitCodeName\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    build {\n      buildUUID\n    }\n  }\n": typeof types.BazelInvocationNodeFragmentDoc,
    "\n  query FindBuilds(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BuildOrder\n    $where: BuildWhereInput\n  ) {\n    findBuilds(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BuildNode\n        }\n      }\n    }\n  }\n": typeof types.FindBuildsDocument,
    "\n  fragment BuildNode on Build {\n    id\n    buildUUID\n    timestamp\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n  }\n": typeof types.BuildNodeFragmentDoc,
    "\n  query CheckIfInvocationExists(\n    $invocationID: UUID!\n  ){\n    getBazelInvocation(invocationID: $invocationID){\n      id\n    }\n  }\n": typeof types.CheckIfInvocationExistsDocument,
    "\n  query GetInvocationTargetsForInvocation(\n    $invocationID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where){\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            id\n            success\n            abortReason\n            durationInMs\n            failureMessage\n            tags\n            target {\n              id\n              label\n              aspect\n              targetKind\n              instanceName {\n                name\n              }\n            }\n          }\n        }\n      }\n      numTotal: invocationTargets {\n        totalCount\n      }\n      numSuccessful: invocationTargets(where: { success: true }) {\n        totalCount\n      }\n      numSkipped: invocationTargets(where: {abortReason: SKIPPED}) {\n        totalCount\n      }\n    }\n  }\n": typeof types.GetInvocationTargetsForInvocationDocument,
    "\n  query GetTargetsList(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ){\n    findTargets (after: $after, first: $first, before: $before, last: $last, where: $where){\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetTargetsListDocument,
    "\n  query GetInvocationTargetsForTarget(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        edges {\n          node {\n            id\n            success\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetInvocationTargetsForTargetDocument,
    "\n  query GetTests(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ) {\n    findTargets(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetTestsDocument,
    "\n  query GetTestsForTarget(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n  findTestSummaries(\n    after: $after\n    first: $first\n    before: $before\n    last: $last\n    orderBy: $orderBy\n    where: $where\n  ) {\n    pageInfo {\n      startCursor\n      endCursor\n      hasNextPage\n      hasPreviousPage\n    }\n    edges {\n      node {\n        id\n        overallStatus\n        invocationTarget {\n          bazelInvocation {\n            invocationID\n          }\n        }\n      }\n    }\n  }\n}\n": typeof types.GetTestsForTargetDocument,
    "\n  query GetTestsForInvocation(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ) {\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            target {\n              id\n              instanceName {\n                name\n              }\n              label\n              aspect\n              targetKind\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetTestsForInvocationDocument,
    "\n  query FindBuildByUUID(\n    $buildUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    getBuild(buildUUID: $buildUUID) {\n      id\n      buildUUID\n      timestamp\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            id\n            key\n            value\n          }\n        }\n      }\n      invocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            ...GetBuildInvocation\n          }\n        }\n      }\n    }\n  }\n": typeof types.FindBuildByUuidDocument,
    "\n  fragment GetBuildInvocation on BazelInvocation {\n    id\n    invocationID\n    username\n    endedAt\n    startedAt\n    exitCodeName\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n  }\n": typeof types.GetBuildInvocationFragmentDoc,
    "\n  query GetTargetDetails(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargetsTotalDurationMillis\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        totalCount\n        edges {\n          node {\n            id\n            success\n            durationInMs\n            abortReason\n            failureMessage\n            tags\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetTargetDetailsDocument,
    "\n    query GetTestDetails(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          runCount\n          attemptCount\n          shardCount\n          firstStartTime\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetTestDetailsDocument,
    "\n  query FindBuildTimes(\n    $first: Int!\n  \t$where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(first: $first, where: $where ) {\n      pageInfo{\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n\n      }\n      totalCount\n      edges {\n        node {\n          invocationID\n          startedAt\n          endedAt\n        }\n      }\n    }\n  }\n": typeof types.FindBuildTimesDocument,
    "\n  query GetBazelInvocationCommon($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommon\n    }\n  }\n": typeof types.GetBazelInvocationCommonDocument,
    "\n  fragment BazelInvocationCommon on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      name\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    username\n    authenticatedUser {\n      displayName\n      userUUID\n    }\n    metrics {\n      id\n      actionSummary {\n        id\n      }\n      artifactMetrics {\n        id\n      }\n      memoryMetrics {\n        id\n      }\n      timingMetrics {\n        id\n      }\n      networkMetrics {\n        id\n      }\n    }\n    build {\n      id\n      buildUUID\n    }\n    actions {\n      id\n    }\n    profile {\n      id\n      name\n      digest\n      sizeInBytes\n      digestFunction\n    }\n    sourceControl {\n      id\n    }\n    tags {\n      totalCount\n    }\n  }\n": typeof types.BazelInvocationCommonFragmentDoc,
    "\n  query GetBazelInvocationActionStatistics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        actionSummary {\n          ...BazelInvocationActionSummary\n          }\n      }\n    }\n  }\n": typeof types.GetBazelInvocationActionStatisticsDocument,
    "\n  fragment BazelInvocationActionSummary on ActionSummary {\n    id\n    actionsExecuted\n    actionCacheStatistics {\n      id\n      loadTimeInMs\n      saveTimeInMs\n      hits\n      misses\n      sizeInBytes\n      missDetails {\n        id\n        count\n        reason\n      }\n    }\n    runnerCount {\n      id\n      actionsExecuted\n      name\n      execKind\n    }\n    actionData {\n      id\n      mnemonic\n      userTime\n      systemTime\n      actionsExecuted\n    }\n  }\n": typeof types.BazelInvocationActionSummaryFragmentDoc,
    "\n  query GetBazelInvocationActions($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      instanceName {\n        id\n        name\n      }\n      actions {\n        ...BazelInvocationActions\n      }\n    }\n  }\n": typeof types.GetBazelInvocationActionsDocument,
    "\n  fragment BazelInvocationActions on Action {\n    id\n    label\n    type\n    success\n    exitCode\n    commandLine\n    startTime\n    endTime\n    failureCode\n    failureMessage\n    stdoutHash\n    stdoutSizeBytes\n    stdoutHashFunction\n    stderrHash\n    stderrSizeBytes\n    stderrHashFunction\n    configuration {\n      id\n      configurationID\n      mnemonic\n      platformName\n      cpu\n      makeVariables\n    }\n  }\n": typeof types.BazelInvocationActionsFragmentDoc,
    "\n  query GetBazelInvocationArtifactMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        artifactMetrics {\n          ...BazelInvocationArtifactMetrics\n          }\n      }\n    }\n  }\n": typeof types.GetBazelInvocationArtifactMetricsDocument,
    "\n  fragment BazelInvocationArtifactMetrics on ArtifactMetrics {\n    id\n    sourceArtifactsReadCount\n    sourceArtifactsReadSizeInBytes\n    outputArtifactsSeenCount\n    outputArtifactsSeenSizeInBytes\n    outputArtifactsFromActionCacheCount\n    outputArtifactsFromActionCacheSizeInBytes\n    topLevelArtifactsCount\n    topLevelArtifactsSizeInBytes\n  }\n": typeof types.BazelInvocationArtifactMetricsFragmentDoc,
    "\n  query GetBazelInvocationCommandline($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommandline\n    }\n  }\n": typeof types.GetBazelInvocationCommandlineDocument,
    "\n  fragment BazelInvocationCommandline on BazelInvocation {\n    id\n    invocationID\n    canonicalCommandLine\n    originalCommandLine\n    optionsParsed\n    environmentVariables\n  }\n": typeof types.BazelInvocationCommandlineFragmentDoc,
    "\n  query GetBazelInvocationOverview($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationOverview\n    }\n  }\n": typeof types.GetBazelInvocationOverviewDocument,
    "\n  fragment BazelInvocationOverview on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      id\n      name\n    }\n    hostname\n    connectionMetadata {\n      id\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n    configurations {\n      id\n      cpu\n      mnemonic\n    }\n    numFetches\n    bazelVersion\n  }\n": typeof types.BazelInvocationOverviewFragmentDoc,
    "\n  query GetBazelInvocationLog($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationLog\n    }\n  }\n": typeof types.GetBazelInvocationLogDocument,
    "\n  fragment BazelInvocationLog on BazelInvocation {\n    id\n    invocationID\n    originalCommandLine\n  }\n": typeof types.BazelInvocationLogFragmentDoc,
    "\n  query GetBazelInvocationMemoryMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        memoryMetrics {\n          ...BazelInvocationMemoryMetrics\n          }\n      }\n    }\n  }\n": typeof types.GetBazelInvocationMemoryMetricsDocument,
    "\n  fragment BazelInvocationMemoryMetrics on MemoryMetrics {\n    id\n    usedHeapSizePostBuild\n    peakPostGcHeapSize\n    peakPostGcTenuredSpaceHeapSize\n    garbageMetrics {\n      id\n      garbageCollected\n      type\n    }\n  }\n": typeof types.BazelInvocationMemoryMetricsFragmentDoc,
    "\n  query GetBazelInvocationSourceControl($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      sourceControl {\n        ...BazelInvocationSourceControl\n      }\n    }\n  }\n": typeof types.GetBazelInvocationSourceControlDocument,
    "\n  fragment BazelInvocationSourceControl on SourceControl {\n    id\n    repo\n    repoURL\n    ref\n    refURL\n    commit\n    commitURL\n  }\n": typeof types.BazelInvocationSourceControlFragmentDoc,
    "\n  query GetBazelInvocationSystemMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        timingMetrics {\n          ...BazelInvocationTimingMetrics\n        }\n        networkMetrics {\n          id\n          systemNetworkStats {\n            ...BazelInvocationSystemNetworkStats\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetBazelInvocationSystemMetricsDocument,
    "\n  fragment BazelInvocationTimingMetrics on TimingMetrics {\n    id\n    cpuTimeInMs\n    wallTimeInMs\n    analysisPhaseTimeInMs\n    executionPhaseTimeInMs\n    actionsExecutionStartInMs\n  }\n": typeof types.BazelInvocationTimingMetricsFragmentDoc,
    "\n  fragment BazelInvocationSystemNetworkStats on SystemNetworkStats {\n    id\n    bytesSent\n    bytesRecv\n    packetsSent\n    packetsRecv\n    peakBytesSentPerSec\n    peakBytesRecvPerSec\n    peakPacketsSentPerSec\n    peakPacketsRecvPerSec\n  }\n": typeof types.BazelInvocationSystemNetworkStatsFragmentDoc,
    "\n  query GetBazelInvocationTags($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            ...BazelInvocationTags\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetBazelInvocationTagsDocument,
    "\n  fragment BazelInvocationTags on InvocationTag {\n    id\n    key\n    value\n  }\n": typeof types.BazelInvocationTagsFragmentDoc,
    "\n  query GetBazelInvocationTargets($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        targetMetrics {\n          ...BazelInvocationTargetMetrics\n          }\n      }\n    }\n  }\n": typeof types.GetBazelInvocationTargetsDocument,
    "\n  fragment BazelInvocationTargetMetrics on TargetMetrics {\n    id\n    targetsLoaded\n    targetsConfigured\n    targetsConfiguredNotIncludingAspects\n  }\n": typeof types.BazelInvocationTargetMetricsFragmentDoc,
    "\n  query getTargetMetadata($id: ID!) {\n    findTargets(where: { id: $id }) {\n      edges {\n        node {\n          id\n          aspect\n          instanceName {\n            name\n          }\n          label\n          targetKind\n        }\n      }\n    }\n  }\n": typeof types.GetTargetMetadataDocument,
    "\n  query GetAuthenticatedUser(\n    $userUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $bazelInvocationsOrderBy: BazelInvocationOrder\n    $bazelInvocationsWhere: BazelInvocationWhereInput\n  ) {\n    getAuthenticatedUser(userUUID: $userUUID) {\n      ...AuthenticatedUserNodeFragment\n    }\n  }\n": typeof types.GetAuthenticatedUserDocument,
    "\n  fragment AuthenticatedUserNodeFragment on AuthenticatedUser {\n    id\n    displayName\n    userInfo\n    userUUID\n    bazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $bazelInvocationsOrderBy, where: $bazelInvocationsWhere) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          invocationID\n          build {\n            id\n            buildUUID\n          }\n          endedAt\n          startedAt\n          exitCodeName\n          connectionMetadata {\n            id\n            connectionLastOpenAt\n            timeSinceLastConnectionMillis\n          }\n        }\n      }\n    }\n  }\n": typeof types.AuthenticatedUserNodeFragmentFragmentDoc,
};
const documents: Documents = {
    "\n  query FindBazelInvocations(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BazelInvocationNode\n        }\n      }\n    }\n  }\n": types.FindBazelInvocationsDocument,
    "\n  fragment BazelInvocationNode on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    username\n    authenticatedUser {\n      userUUID\n      displayName\n    }\n    endedAt\n    exitCodeName\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    build {\n      buildUUID\n    }\n  }\n": types.BazelInvocationNodeFragmentDoc,
    "\n  query FindBuilds(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BuildOrder\n    $where: BuildWhereInput\n  ) {\n    findBuilds(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BuildNode\n        }\n      }\n    }\n  }\n": types.FindBuildsDocument,
    "\n  fragment BuildNode on Build {\n    id\n    buildUUID\n    timestamp\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n  }\n": types.BuildNodeFragmentDoc,
    "\n  query CheckIfInvocationExists(\n    $invocationID: UUID!\n  ){\n    getBazelInvocation(invocationID: $invocationID){\n      id\n    }\n  }\n": types.CheckIfInvocationExistsDocument,
    "\n  query GetInvocationTargetsForInvocation(\n    $invocationID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where){\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            id\n            success\n            abortReason\n            durationInMs\n            failureMessage\n            tags\n            target {\n              id\n              label\n              aspect\n              targetKind\n              instanceName {\n                name\n              }\n            }\n          }\n        }\n      }\n      numTotal: invocationTargets {\n        totalCount\n      }\n      numSuccessful: invocationTargets(where: { success: true }) {\n        totalCount\n      }\n      numSkipped: invocationTargets(where: {abortReason: SKIPPED}) {\n        totalCount\n      }\n    }\n  }\n": types.GetInvocationTargetsForInvocationDocument,
    "\n  query GetTargetsList(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ){\n    findTargets (after: $after, first: $first, before: $before, last: $last, where: $where){\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetTargetsListDocument,
    "\n  query GetInvocationTargetsForTarget(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        edges {\n          node {\n            id\n            success\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetInvocationTargetsForTargetDocument,
    "\n  query GetTests(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ) {\n    findTargets(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetTestsDocument,
    "\n  query GetTestsForTarget(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n  findTestSummaries(\n    after: $after\n    first: $first\n    before: $before\n    last: $last\n    orderBy: $orderBy\n    where: $where\n  ) {\n    pageInfo {\n      startCursor\n      endCursor\n      hasNextPage\n      hasPreviousPage\n    }\n    edges {\n      node {\n        id\n        overallStatus\n        invocationTarget {\n          bazelInvocation {\n            invocationID\n          }\n        }\n      }\n    }\n  }\n}\n": types.GetTestsForTargetDocument,
    "\n  query GetTestsForInvocation(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ) {\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            target {\n              id\n              instanceName {\n                name\n              }\n              label\n              aspect\n              targetKind\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetTestsForInvocationDocument,
    "\n  query FindBuildByUUID(\n    $buildUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    getBuild(buildUUID: $buildUUID) {\n      id\n      buildUUID\n      timestamp\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            id\n            key\n            value\n          }\n        }\n      }\n      invocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            ...GetBuildInvocation\n          }\n        }\n      }\n    }\n  }\n": types.FindBuildByUuidDocument,
    "\n  fragment GetBuildInvocation on BazelInvocation {\n    id\n    invocationID\n    username\n    endedAt\n    startedAt\n    exitCodeName\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n  }\n": types.GetBuildInvocationFragmentDoc,
    "\n  query GetTargetDetails(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargetsTotalDurationMillis\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        totalCount\n        edges {\n          node {\n            id\n            success\n            durationInMs\n            abortReason\n            failureMessage\n            tags\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetTargetDetailsDocument,
    "\n    query GetTestDetails(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          runCount\n          attemptCount\n          shardCount\n          firstStartTime\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetTestDetailsDocument,
    "\n  query FindBuildTimes(\n    $first: Int!\n  \t$where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(first: $first, where: $where ) {\n      pageInfo{\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n\n      }\n      totalCount\n      edges {\n        node {\n          invocationID\n          startedAt\n          endedAt\n        }\n      }\n    }\n  }\n": types.FindBuildTimesDocument,
    "\n  query GetBazelInvocationCommon($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommon\n    }\n  }\n": types.GetBazelInvocationCommonDocument,
    "\n  fragment BazelInvocationCommon on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      name\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    username\n    authenticatedUser {\n      displayName\n      userUUID\n    }\n    metrics {\n      id\n      actionSummary {\n        id\n      }\n      artifactMetrics {\n        id\n      }\n      memoryMetrics {\n        id\n      }\n      timingMetrics {\n        id\n      }\n      networkMetrics {\n        id\n      }\n    }\n    build {\n      id\n      buildUUID\n    }\n    actions {\n      id\n    }\n    profile {\n      id\n      name\n      digest\n      sizeInBytes\n      digestFunction\n    }\n    sourceControl {\n      id\n    }\n    tags {\n      totalCount\n    }\n  }\n": types.BazelInvocationCommonFragmentDoc,
    "\n  query GetBazelInvocationActionStatistics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        actionSummary {\n          ...BazelInvocationActionSummary\n          }\n      }\n    }\n  }\n": types.GetBazelInvocationActionStatisticsDocument,
    "\n  fragment BazelInvocationActionSummary on ActionSummary {\n    id\n    actionsExecuted\n    actionCacheStatistics {\n      id\n      loadTimeInMs\n      saveTimeInMs\n      hits\n      misses\n      sizeInBytes\n      missDetails {\n        id\n        count\n        reason\n      }\n    }\n    runnerCount {\n      id\n      actionsExecuted\n      name\n      execKind\n    }\n    actionData {\n      id\n      mnemonic\n      userTime\n      systemTime\n      actionsExecuted\n    }\n  }\n": types.BazelInvocationActionSummaryFragmentDoc,
    "\n  query GetBazelInvocationActions($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      instanceName {\n        id\n        name\n      }\n      actions {\n        ...BazelInvocationActions\n      }\n    }\n  }\n": types.GetBazelInvocationActionsDocument,
    "\n  fragment BazelInvocationActions on Action {\n    id\n    label\n    type\n    success\n    exitCode\n    commandLine\n    startTime\n    endTime\n    failureCode\n    failureMessage\n    stdoutHash\n    stdoutSizeBytes\n    stdoutHashFunction\n    stderrHash\n    stderrSizeBytes\n    stderrHashFunction\n    configuration {\n      id\n      configurationID\n      mnemonic\n      platformName\n      cpu\n      makeVariables\n    }\n  }\n": types.BazelInvocationActionsFragmentDoc,
    "\n  query GetBazelInvocationArtifactMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        artifactMetrics {\n          ...BazelInvocationArtifactMetrics\n          }\n      }\n    }\n  }\n": types.GetBazelInvocationArtifactMetricsDocument,
    "\n  fragment BazelInvocationArtifactMetrics on ArtifactMetrics {\n    id\n    sourceArtifactsReadCount\n    sourceArtifactsReadSizeInBytes\n    outputArtifactsSeenCount\n    outputArtifactsSeenSizeInBytes\n    outputArtifactsFromActionCacheCount\n    outputArtifactsFromActionCacheSizeInBytes\n    topLevelArtifactsCount\n    topLevelArtifactsSizeInBytes\n  }\n": types.BazelInvocationArtifactMetricsFragmentDoc,
    "\n  query GetBazelInvocationCommandline($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommandline\n    }\n  }\n": types.GetBazelInvocationCommandlineDocument,
    "\n  fragment BazelInvocationCommandline on BazelInvocation {\n    id\n    invocationID\n    canonicalCommandLine\n    originalCommandLine\n    optionsParsed\n    environmentVariables\n  }\n": types.BazelInvocationCommandlineFragmentDoc,
    "\n  query GetBazelInvocationOverview($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationOverview\n    }\n  }\n": types.GetBazelInvocationOverviewDocument,
    "\n  fragment BazelInvocationOverview on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      id\n      name\n    }\n    hostname\n    connectionMetadata {\n      id\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n    configurations {\n      id\n      cpu\n      mnemonic\n    }\n    numFetches\n    bazelVersion\n  }\n": types.BazelInvocationOverviewFragmentDoc,
    "\n  query GetBazelInvocationLog($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationLog\n    }\n  }\n": types.GetBazelInvocationLogDocument,
    "\n  fragment BazelInvocationLog on BazelInvocation {\n    id\n    invocationID\n    originalCommandLine\n  }\n": types.BazelInvocationLogFragmentDoc,
    "\n  query GetBazelInvocationMemoryMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        memoryMetrics {\n          ...BazelInvocationMemoryMetrics\n          }\n      }\n    }\n  }\n": types.GetBazelInvocationMemoryMetricsDocument,
    "\n  fragment BazelInvocationMemoryMetrics on MemoryMetrics {\n    id\n    usedHeapSizePostBuild\n    peakPostGcHeapSize\n    peakPostGcTenuredSpaceHeapSize\n    garbageMetrics {\n      id\n      garbageCollected\n      type\n    }\n  }\n": types.BazelInvocationMemoryMetricsFragmentDoc,
    "\n  query GetBazelInvocationSourceControl($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      sourceControl {\n        ...BazelInvocationSourceControl\n      }\n    }\n  }\n": types.GetBazelInvocationSourceControlDocument,
    "\n  fragment BazelInvocationSourceControl on SourceControl {\n    id\n    repo\n    repoURL\n    ref\n    refURL\n    commit\n    commitURL\n  }\n": types.BazelInvocationSourceControlFragmentDoc,
    "\n  query GetBazelInvocationSystemMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        timingMetrics {\n          ...BazelInvocationTimingMetrics\n        }\n        networkMetrics {\n          id\n          systemNetworkStats {\n            ...BazelInvocationSystemNetworkStats\n          }\n        }\n      }\n    }\n  }\n": types.GetBazelInvocationSystemMetricsDocument,
    "\n  fragment BazelInvocationTimingMetrics on TimingMetrics {\n    id\n    cpuTimeInMs\n    wallTimeInMs\n    analysisPhaseTimeInMs\n    executionPhaseTimeInMs\n    actionsExecutionStartInMs\n  }\n": types.BazelInvocationTimingMetricsFragmentDoc,
    "\n  fragment BazelInvocationSystemNetworkStats on SystemNetworkStats {\n    id\n    bytesSent\n    bytesRecv\n    packetsSent\n    packetsRecv\n    peakBytesSentPerSec\n    peakBytesRecvPerSec\n    peakPacketsSentPerSec\n    peakPacketsRecvPerSec\n  }\n": types.BazelInvocationSystemNetworkStatsFragmentDoc,
    "\n  query GetBazelInvocationTags($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            ...BazelInvocationTags\n          }\n        }\n      }\n    }\n  }\n": types.GetBazelInvocationTagsDocument,
    "\n  fragment BazelInvocationTags on InvocationTag {\n    id\n    key\n    value\n  }\n": types.BazelInvocationTagsFragmentDoc,
    "\n  query GetBazelInvocationTargets($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        targetMetrics {\n          ...BazelInvocationTargetMetrics\n          }\n      }\n    }\n  }\n": types.GetBazelInvocationTargetsDocument,
    "\n  fragment BazelInvocationTargetMetrics on TargetMetrics {\n    id\n    targetsLoaded\n    targetsConfigured\n    targetsConfiguredNotIncludingAspects\n  }\n": types.BazelInvocationTargetMetricsFragmentDoc,
    "\n  query getTargetMetadata($id: ID!) {\n    findTargets(where: { id: $id }) {\n      edges {\n        node {\n          id\n          aspect\n          instanceName {\n            name\n          }\n          label\n          targetKind\n        }\n      }\n    }\n  }\n": types.GetTargetMetadataDocument,
    "\n  query GetAuthenticatedUser(\n    $userUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $bazelInvocationsOrderBy: BazelInvocationOrder\n    $bazelInvocationsWhere: BazelInvocationWhereInput\n  ) {\n    getAuthenticatedUser(userUUID: $userUUID) {\n      ...AuthenticatedUserNodeFragment\n    }\n  }\n": types.GetAuthenticatedUserDocument,
    "\n  fragment AuthenticatedUserNodeFragment on AuthenticatedUser {\n    id\n    displayName\n    userInfo\n    userUUID\n    bazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $bazelInvocationsOrderBy, where: $bazelInvocationsWhere) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          invocationID\n          build {\n            id\n            buildUUID\n          }\n          endedAt\n          startedAt\n          exitCodeName\n          connectionMetadata {\n            id\n            connectionLastOpenAt\n            timeSinceLastConnectionMillis\n          }\n        }\n      }\n    }\n  }\n": types.AuthenticatedUserNodeFragmentFragmentDoc,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query FindBazelInvocations(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BazelInvocationNode\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindBazelInvocations(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BazelInvocationNode\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationNode on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    username\n    authenticatedUser {\n      userUUID\n      displayName\n    }\n    endedAt\n    exitCodeName\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    build {\n      buildUUID\n    }\n  }\n"): (typeof documents)["\n  fragment BazelInvocationNode on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    username\n    authenticatedUser {\n      userUUID\n      displayName\n    }\n    endedAt\n    exitCodeName\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    build {\n      buildUUID\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query FindBuilds(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BuildOrder\n    $where: BuildWhereInput\n  ) {\n    findBuilds(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BuildNode\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindBuilds(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BuildOrder\n    $where: BuildWhereInput\n  ) {\n    findBuilds(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          ...BuildNode\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BuildNode on Build {\n    id\n    buildUUID\n    timestamp\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment BuildNode on Build {\n    id\n    buildUUID\n    timestamp\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query CheckIfInvocationExists(\n    $invocationID: UUID!\n  ){\n    getBazelInvocation(invocationID: $invocationID){\n      id\n    }\n  }\n"): (typeof documents)["\n  query CheckIfInvocationExists(\n    $invocationID: UUID!\n  ){\n    getBazelInvocation(invocationID: $invocationID){\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetInvocationTargetsForInvocation(\n    $invocationID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where){\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            id\n            success\n            abortReason\n            durationInMs\n            failureMessage\n            tags\n            target {\n              id\n              label\n              aspect\n              targetKind\n              instanceName {\n                name\n              }\n            }\n          }\n        }\n      }\n      numTotal: invocationTargets {\n        totalCount\n      }\n      numSuccessful: invocationTargets(where: { success: true }) {\n        totalCount\n      }\n      numSkipped: invocationTargets(where: {abortReason: SKIPPED}) {\n        totalCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetInvocationTargetsForInvocation(\n    $invocationID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where){\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            id\n            success\n            abortReason\n            durationInMs\n            failureMessage\n            tags\n            target {\n              id\n              label\n              aspect\n              targetKind\n              instanceName {\n                name\n              }\n            }\n          }\n        }\n      }\n      numTotal: invocationTargets {\n        totalCount\n      }\n      numSuccessful: invocationTargets(where: { success: true }) {\n        totalCount\n      }\n      numSkipped: invocationTargets(where: {abortReason: SKIPPED}) {\n        totalCount\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTargetsList(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ){\n    findTargets (after: $after, first: $first, before: $before, last: $last, where: $where){\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetTargetsList(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ){\n    findTargets (after: $after, first: $first, before: $before, last: $last, where: $where){\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetInvocationTargetsForTarget(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        edges {\n          node {\n            id\n            success\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetInvocationTargetsForTarget(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        edges {\n          node {\n            id\n            success\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTests(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ) {\n    findTargets(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetTests(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $where: TargetWhereInput\n  ) {\n    findTargets(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          label\n          aspect\n          targetKind\n          instanceName {\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTestsForTarget(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n  findTestSummaries(\n    after: $after\n    first: $first\n    before: $before\n    last: $last\n    orderBy: $orderBy\n    where: $where\n  ) {\n    pageInfo {\n      startCursor\n      endCursor\n      hasNextPage\n      hasPreviousPage\n    }\n    edges {\n      node {\n        id\n        overallStatus\n        invocationTarget {\n          bazelInvocation {\n            invocationID\n          }\n        }\n      }\n    }\n  }\n}\n"): (typeof documents)["\n  query GetTestsForTarget(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n  findTestSummaries(\n    after: $after\n    first: $first\n    before: $before\n    last: $last\n    orderBy: $orderBy\n    where: $where\n  ) {\n    pageInfo {\n      startCursor\n      endCursor\n      hasNextPage\n      hasPreviousPage\n    }\n    edges {\n      node {\n        id\n        overallStatus\n        invocationTarget {\n          bazelInvocation {\n            invocationID\n          }\n        }\n      }\n    }\n  }\n}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTestsForInvocation(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ) {\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            target {\n              id\n              instanceName {\n                name\n              }\n              label\n              aspect\n              targetKind\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetTestsForInvocation(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ) {\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            target {\n              id\n              instanceName {\n                name\n              }\n              label\n              aspect\n              targetKind\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query FindBuildByUUID(\n    $buildUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    getBuild(buildUUID: $buildUUID) {\n      id\n      buildUUID\n      timestamp\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            id\n            key\n            value\n          }\n        }\n      }\n      invocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            ...GetBuildInvocation\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindBuildByUUID(\n    $buildUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: BazelInvocationOrder\n    $where: BazelInvocationWhereInput\n  ) {\n    getBuild(buildUUID: $buildUUID) {\n      id\n      buildUUID\n      timestamp\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            id\n            key\n            value\n          }\n        }\n      }\n      invocations(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        edges {\n          node {\n            ...GetBuildInvocation\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment GetBuildInvocation on BazelInvocation {\n    id\n    invocationID\n    username\n    endedAt\n    startedAt\n    exitCodeName\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n  }\n"): (typeof documents)["\n  fragment GetBuildInvocation on BazelInvocation {\n    id\n    invocationID\n    username\n    endedAt\n    startedAt\n    exitCodeName\n    tags {\n      edges {\n        node {\n          id\n          key\n          value\n        }\n      }\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetTargetDetails(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargetsTotalDurationMillis\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        totalCount\n        edges {\n          node {\n            id\n            success\n            durationInMs\n            abortReason\n            failureMessage\n            tags\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetTargetDetails(\n    $instanceName: String!\n    $label: String!\n    $aspect: String!\n    $targetKind: String!\n\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: InvocationTargetOrder\n    $where: InvocationTargetWhereInput\n  ){\n    getTarget (instanceName: $instanceName, label: $label, aspect: $aspect, targetKind: $targetKind){\n      invocationTargetsTotalDurationMillis\n      invocationTargets(after: $after, first: $first, before: $before, last: $last, orderBy: $orderBy, where: $where) {\n        pageInfo {\n          startCursor\n          endCursor\n          hasNextPage\n          hasPreviousPage\n        }\n        totalCount\n        edges {\n          node {\n            id\n            success\n            durationInMs\n            abortReason\n            failureMessage\n            tags\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetTestDetails(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          runCount\n          attemptCount\n          shardCount\n          firstStartTime\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n    query GetTestDetails(\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $orderBy: TestSummaryOrder\n    $where: TestSummaryWhereInput\n  ){\n    findTestSummaries(\n      after: $after\n      first: $first\n      before: $before\n      last: $last\n      orderBy: $orderBy\n      where: $where\n    ) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          overallStatus\n          runCount\n          attemptCount\n          shardCount\n          firstStartTime\n          totalRunDurationInMs\n          testResults {\n            cachedLocally\n            cachedRemotely\n          }\n          invocationTarget {\n            bazelInvocation {\n              invocationID\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query FindBuildTimes(\n    $first: Int!\n  \t$where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(first: $first, where: $where ) {\n      pageInfo{\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n\n      }\n      totalCount\n      edges {\n        node {\n          invocationID\n          startedAt\n          endedAt\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query FindBuildTimes(\n    $first: Int!\n  \t$where: BazelInvocationWhereInput\n  ) {\n    findBazelInvocations(first: $first, where: $where ) {\n      pageInfo{\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n\n      }\n      totalCount\n      edges {\n        node {\n          invocationID\n          startedAt\n          endedAt\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationCommon($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommon\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationCommon($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommon\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationCommon on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      name\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    username\n    authenticatedUser {\n      displayName\n      userUUID\n    }\n    metrics {\n      id\n      actionSummary {\n        id\n      }\n      artifactMetrics {\n        id\n      }\n      memoryMetrics {\n        id\n      }\n      timingMetrics {\n        id\n      }\n      networkMetrics {\n        id\n      }\n    }\n    build {\n      id\n      buildUUID\n    }\n    actions {\n      id\n    }\n    profile {\n      id\n      name\n      digest\n      sizeInBytes\n      digestFunction\n    }\n    sourceControl {\n      id\n    }\n    tags {\n      totalCount\n    }\n  }\n"): (typeof documents)["\n  fragment BazelInvocationCommon on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      name\n    }\n    connectionMetadata {\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    username\n    authenticatedUser {\n      displayName\n      userUUID\n    }\n    metrics {\n      id\n      actionSummary {\n        id\n      }\n      artifactMetrics {\n        id\n      }\n      memoryMetrics {\n        id\n      }\n      timingMetrics {\n        id\n      }\n      networkMetrics {\n        id\n      }\n    }\n    build {\n      id\n      buildUUID\n    }\n    actions {\n      id\n    }\n    profile {\n      id\n      name\n      digest\n      sizeInBytes\n      digestFunction\n    }\n    sourceControl {\n      id\n    }\n    tags {\n      totalCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationActionStatistics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        actionSummary {\n          ...BazelInvocationActionSummary\n          }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationActionStatistics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        actionSummary {\n          ...BazelInvocationActionSummary\n          }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationActionSummary on ActionSummary {\n    id\n    actionsExecuted\n    actionCacheStatistics {\n      id\n      loadTimeInMs\n      saveTimeInMs\n      hits\n      misses\n      sizeInBytes\n      missDetails {\n        id\n        count\n        reason\n      }\n    }\n    runnerCount {\n      id\n      actionsExecuted\n      name\n      execKind\n    }\n    actionData {\n      id\n      mnemonic\n      userTime\n      systemTime\n      actionsExecuted\n    }\n  }\n"): (typeof documents)["\n  fragment BazelInvocationActionSummary on ActionSummary {\n    id\n    actionsExecuted\n    actionCacheStatistics {\n      id\n      loadTimeInMs\n      saveTimeInMs\n      hits\n      misses\n      sizeInBytes\n      missDetails {\n        id\n        count\n        reason\n      }\n    }\n    runnerCount {\n      id\n      actionsExecuted\n      name\n      execKind\n    }\n    actionData {\n      id\n      mnemonic\n      userTime\n      systemTime\n      actionsExecuted\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationActions($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      instanceName {\n        id\n        name\n      }\n      actions {\n        ...BazelInvocationActions\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationActions($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      instanceName {\n        id\n        name\n      }\n      actions {\n        ...BazelInvocationActions\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationActions on Action {\n    id\n    label\n    type\n    success\n    exitCode\n    commandLine\n    startTime\n    endTime\n    failureCode\n    failureMessage\n    stdoutHash\n    stdoutSizeBytes\n    stdoutHashFunction\n    stderrHash\n    stderrSizeBytes\n    stderrHashFunction\n    configuration {\n      id\n      configurationID\n      mnemonic\n      platformName\n      cpu\n      makeVariables\n    }\n  }\n"): (typeof documents)["\n  fragment BazelInvocationActions on Action {\n    id\n    label\n    type\n    success\n    exitCode\n    commandLine\n    startTime\n    endTime\n    failureCode\n    failureMessage\n    stdoutHash\n    stdoutSizeBytes\n    stdoutHashFunction\n    stderrHash\n    stderrSizeBytes\n    stderrHashFunction\n    configuration {\n      id\n      configurationID\n      mnemonic\n      platformName\n      cpu\n      makeVariables\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationArtifactMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        artifactMetrics {\n          ...BazelInvocationArtifactMetrics\n          }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationArtifactMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        artifactMetrics {\n          ...BazelInvocationArtifactMetrics\n          }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationArtifactMetrics on ArtifactMetrics {\n    id\n    sourceArtifactsReadCount\n    sourceArtifactsReadSizeInBytes\n    outputArtifactsSeenCount\n    outputArtifactsSeenSizeInBytes\n    outputArtifactsFromActionCacheCount\n    outputArtifactsFromActionCacheSizeInBytes\n    topLevelArtifactsCount\n    topLevelArtifactsSizeInBytes\n  }\n"): (typeof documents)["\n  fragment BazelInvocationArtifactMetrics on ArtifactMetrics {\n    id\n    sourceArtifactsReadCount\n    sourceArtifactsReadSizeInBytes\n    outputArtifactsSeenCount\n    outputArtifactsSeenSizeInBytes\n    outputArtifactsFromActionCacheCount\n    outputArtifactsFromActionCacheSizeInBytes\n    topLevelArtifactsCount\n    topLevelArtifactsSizeInBytes\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationCommandline($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommandline\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationCommandline($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationCommandline\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationCommandline on BazelInvocation {\n    id\n    invocationID\n    canonicalCommandLine\n    originalCommandLine\n    optionsParsed\n    environmentVariables\n  }\n"): (typeof documents)["\n  fragment BazelInvocationCommandline on BazelInvocation {\n    id\n    invocationID\n    canonicalCommandLine\n    originalCommandLine\n    optionsParsed\n    environmentVariables\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationOverview($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationOverview\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationOverview($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationOverview\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationOverview on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      id\n      name\n    }\n    hostname\n    connectionMetadata {\n      id\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n    configurations {\n      id\n      cpu\n      mnemonic\n    }\n    numFetches\n    bazelVersion\n  }\n"): (typeof documents)["\n  fragment BazelInvocationOverview on BazelInvocation {\n    id\n    invocationID\n    startedAt\n    endedAt\n    exitCodeName\n    instanceName {\n      id\n      name\n    }\n    hostname\n    connectionMetadata {\n      id\n      connectionLastOpenAt\n      timeSinceLastConnectionMillis\n    }\n    originalCommandLine\n    configurations {\n      id\n      cpu\n      mnemonic\n    }\n    numFetches\n    bazelVersion\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationLog($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationLog\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationLog($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      ...BazelInvocationLog\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationLog on BazelInvocation {\n    id\n    invocationID\n    originalCommandLine\n  }\n"): (typeof documents)["\n  fragment BazelInvocationLog on BazelInvocation {\n    id\n    invocationID\n    originalCommandLine\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationMemoryMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        memoryMetrics {\n          ...BazelInvocationMemoryMetrics\n          }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationMemoryMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        memoryMetrics {\n          ...BazelInvocationMemoryMetrics\n          }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationMemoryMetrics on MemoryMetrics {\n    id\n    usedHeapSizePostBuild\n    peakPostGcHeapSize\n    peakPostGcTenuredSpaceHeapSize\n    garbageMetrics {\n      id\n      garbageCollected\n      type\n    }\n  }\n"): (typeof documents)["\n  fragment BazelInvocationMemoryMetrics on MemoryMetrics {\n    id\n    usedHeapSizePostBuild\n    peakPostGcHeapSize\n    peakPostGcTenuredSpaceHeapSize\n    garbageMetrics {\n      id\n      garbageCollected\n      type\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationSourceControl($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      sourceControl {\n        ...BazelInvocationSourceControl\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationSourceControl($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      sourceControl {\n        ...BazelInvocationSourceControl\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationSourceControl on SourceControl {\n    id\n    repo\n    repoURL\n    ref\n    refURL\n    commit\n    commitURL\n  }\n"): (typeof documents)["\n  fragment BazelInvocationSourceControl on SourceControl {\n    id\n    repo\n    repoURL\n    ref\n    refURL\n    commit\n    commitURL\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationSystemMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        timingMetrics {\n          ...BazelInvocationTimingMetrics\n        }\n        networkMetrics {\n          id\n          systemNetworkStats {\n            ...BazelInvocationSystemNetworkStats\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationSystemMetrics($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        timingMetrics {\n          ...BazelInvocationTimingMetrics\n        }\n        networkMetrics {\n          id\n          systemNetworkStats {\n            ...BazelInvocationSystemNetworkStats\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationTimingMetrics on TimingMetrics {\n    id\n    cpuTimeInMs\n    wallTimeInMs\n    analysisPhaseTimeInMs\n    executionPhaseTimeInMs\n    actionsExecutionStartInMs\n  }\n"): (typeof documents)["\n  fragment BazelInvocationTimingMetrics on TimingMetrics {\n    id\n    cpuTimeInMs\n    wallTimeInMs\n    analysisPhaseTimeInMs\n    executionPhaseTimeInMs\n    actionsExecutionStartInMs\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationSystemNetworkStats on SystemNetworkStats {\n    id\n    bytesSent\n    bytesRecv\n    packetsSent\n    packetsRecv\n    peakBytesSentPerSec\n    peakBytesRecvPerSec\n    peakPacketsSentPerSec\n    peakPacketsRecvPerSec\n  }\n"): (typeof documents)["\n  fragment BazelInvocationSystemNetworkStats on SystemNetworkStats {\n    id\n    bytesSent\n    bytesRecv\n    packetsSent\n    packetsRecv\n    peakBytesSentPerSec\n    peakBytesRecvPerSec\n    peakPacketsSentPerSec\n    peakPacketsRecvPerSec\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationTags($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            ...BazelInvocationTags\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationTags($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      tags(orderBy: { field: KEY, direction: ASC }) {\n        edges {\n          node {\n            ...BazelInvocationTags\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationTags on InvocationTag {\n    id\n    key\n    value\n  }\n"): (typeof documents)["\n  fragment BazelInvocationTags on InvocationTag {\n    id\n    key\n    value\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetBazelInvocationTargets($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        targetMetrics {\n          ...BazelInvocationTargetMetrics\n          }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetBazelInvocationTargets($invocationID: UUID!) {\n    getBazelInvocation(invocationID: $invocationID) {\n      id\n      metrics {\n        id\n        targetMetrics {\n          ...BazelInvocationTargetMetrics\n          }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment BazelInvocationTargetMetrics on TargetMetrics {\n    id\n    targetsLoaded\n    targetsConfigured\n    targetsConfiguredNotIncludingAspects\n  }\n"): (typeof documents)["\n  fragment BazelInvocationTargetMetrics on TargetMetrics {\n    id\n    targetsLoaded\n    targetsConfigured\n    targetsConfiguredNotIncludingAspects\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getTargetMetadata($id: ID!) {\n    findTargets(where: { id: $id }) {\n      edges {\n        node {\n          id\n          aspect\n          instanceName {\n            name\n          }\n          label\n          targetKind\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getTargetMetadata($id: ID!) {\n    findTargets(where: { id: $id }) {\n      edges {\n        node {\n          id\n          aspect\n          instanceName {\n            name\n          }\n          label\n          targetKind\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetAuthenticatedUser(\n    $userUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $bazelInvocationsOrderBy: BazelInvocationOrder\n    $bazelInvocationsWhere: BazelInvocationWhereInput\n  ) {\n    getAuthenticatedUser(userUUID: $userUUID) {\n      ...AuthenticatedUserNodeFragment\n    }\n  }\n"): (typeof documents)["\n  query GetAuthenticatedUser(\n    $userUUID: UUID!\n    $after: Cursor\n    $first: Int\n    $before: Cursor\n    $last: Int\n    $bazelInvocationsOrderBy: BazelInvocationOrder\n    $bazelInvocationsWhere: BazelInvocationWhereInput\n  ) {\n    getAuthenticatedUser(userUUID: $userUUID) {\n      ...AuthenticatedUserNodeFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment AuthenticatedUserNodeFragment on AuthenticatedUser {\n    id\n    displayName\n    userInfo\n    userUUID\n    bazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $bazelInvocationsOrderBy, where: $bazelInvocationsWhere) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          invocationID\n          build {\n            id\n            buildUUID\n          }\n          endedAt\n          startedAt\n          exitCodeName\n          connectionMetadata {\n            id\n            connectionLastOpenAt\n            timeSinceLastConnectionMillis\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment AuthenticatedUserNodeFragment on AuthenticatedUser {\n    id\n    displayName\n    userInfo\n    userUUID\n    bazelInvocations(after: $after, first: $first, before: $before, last: $last, orderBy: $bazelInvocationsOrderBy, where: $bazelInvocationsWhere) {\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n      edges {\n        node {\n          id\n          invocationID\n          build {\n            id\n            buildUUID\n          }\n          endedAt\n          startedAt\n          exitCodeName\n          connectionMetadata {\n            id\n            connectionLastOpenAt\n            timeSinceLastConnectionMillis\n          }\n        }\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;