name: Build frontend

on:
  pull_request:
    branches: ["main"]

jobs:
  publish:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set frontend image tag variables
        run: |
          echo "TIMESTAMP=$(TZ=UTC date --date "@$(git show -s --format=%ct HEAD)" +%Y%m%dT%H%M%SZ)" >> $GITHUB_ENV
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: ./frontend/Dockerfile
          push: false
          tags: ghcr.io/buildbarn/bb-portal-frontend:${{ env.TIMESTAMP }}-${{ env.SHA_SHORT }}
