{
   "jobs": {
      "build_and_test": {
         "name": "Build and test frontend",
         "runs-on": "ubuntu-24.04-arm",
         "steps": [
            {
               "name": "Check out source code",
               "uses": "actions/checkout@v4"
            },
            {
               "name": "Setup Node.js",
               "uses": "actions/setup-node@v4",
               "with": {
                  "node-version-file": "frontend/.nvmrc"
               }
            },
            {
               "name": "Install dependencies",
               "run": "npm ci",
               "working-directory": "frontend"
            },
            {
               "name": "Generate frontend files",
               "run": "npm run generate",
               "working-directory": "frontend"
            },
            {
               "name": "Check if any generated files changed",
               "run": "git add . && git diff --exit-code HEAD --"
            },
            {
               "name": "Test",
               "run": "npm run test",
               "working-directory": "frontend"
            },
            {
               "name": "Build",
               "run": "npm run build",
               "working-directory": "frontend"
            }
         ]
      }
   },
   "name": "Build and test frontend",
   "on": {
      "pull_request": {
         "branches": [
            "main"
         ]
      },
      "push": {
         "branches": [
            "main"
         ]
      }
   }
}
